Repository googleapis/google-cloud-go, pull requests merged in 2020-09, with the labels that each got.

#2803 spanner/spannertest: fix aggregation in query evaluation for empty in…
  spanner/spannertest/db_query.go
  spanner/spannertest/db_test.go
Labels: api: spanner, cla: yes

#2802 spanner/spannertest: implement GetDatabase
  spanner/spannertest/inmem.go
Labels: api: spanner, cla: yes

#2806 feat(security/privateca): start generating apiv1beta1
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  security/privateca/apiv1beta1/certificate_authority_client.go
  security/privateca/apiv1beta1/certificate_authority_client_example_test.go
  security/privateca/apiv1beta1/doc.go
Labels: automerge, cla: yes

#2807 feat(area120/tables): start generating apiv1alpha1
  area120/tables/apiv1alpha1/doc.go
  area120/tables/apiv1alpha1/tables_client.go
  area120/tables/apiv1alpha1/tables_client_example_test.go
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: cla: yes

#2811 fix(pubsub): fix ordering key integration tests
  pubsub/integration_test.go
Labels: api: pubsub, cla: yes

#2773 fix(bigtable): change max valid Timestamp value
  bigtable/bttest/inmem.go
  bigtable/bttest/inmem_test.go
Labels: api: bigtable, automerge, cla: yes

#2815 fix(pubsub): honor option.WithTelemetryDisabled
  pubsub/pubsub.go
  pubsub/trace.go
Labels: api: pubsub, automerge, cla: yes

#2823 spanner/spannertest: support dropping columns
  spanner/spannertest/db.go
Labels: cla: yes

#2674 feat(spanner/spannertest): add support for bool parameter types
  spanner/spannertest/db_eval.go
  spanner/spannertest/db_test.go
  spanner/spannertest/inmem.go
Labels: automerge, cla: yes

#2825 spanner/spansql: update docs on TableAlteration, ColumnAlteration
  spanner/spansql/types.go
Labels: automerge, cla: yes

#2818 test(storage): re-enable full CustomTime test
  storage/integration_test.go
Labels: api: storage, automerge, cla: yes

#2794 fix: support saving custom types that implements PropertyLoadSaver
  datastore/save.go
  datastore/save_test.go
Labels: api: datastore, cla: yes, type: bug

#2415 feat(spanner): add support for NUMERIC data type
  spanner/cmp_test.go
  spanner/integration_test.go
  spanner/protoutils.go
  spanner/row_test.go
  spanner/value.go
  spanner/value_test.go
Labels: api: spanner, cla: yes, do not merge

#2827 chore(spanner): release v1.10.0
  internal/version/version.go
  spanner/CHANGES.md
Labels: api: spanner, cla: yes

#2830 feat(cloudbuild): Start generating apiv1/v3
  internal/gapicgen/generator/config.go
  internal/gapicgen/generator/config_test.go
Labels: automerge, cla: yes

#2726 test(bigtable): capture errors from DeleteTable()
  bigtable/integration_test.go
Labels: api: bigtable, cla: yes, type: cleanup

#2834 fix(spanner): fix flaky numeric tests
  spanner/integration_test.go
Labels: api: spanner, cla: yes

#2720 feat(bigtable): support partial results in InstanceAdminClient.Instan…
  bigtable/admin.go
Labels: api: bigtable, cla: yes, type: feature request

#2661 fix(storage): make Query show Prefix consistently
  storage/integration_test.go
  storage/storage.go
Labels: automerge, cla: yes

#2840 revert(cloudbuild): "feat(cloudbuild): Start generating apiv1/v3"
  internal/gapicgen/generator/config.go
  internal/gapicgen/generator/config_test.go
Labels: automerge, cla: yes

#2842 test(pubsub): remove staging endpoint for sub detach
  pubsub/integration_test.go
Labels: cla: yes

#2838 test(spanner): fix flaky oc_test.go
  spanner/oc_test.go
Labels: cla: yes

#2837 feat(spanner): add KeySetFromKeys function
  spanner/key.go
  spanner/key_test.go
Labels: api: spanner, cla: yes

#2847 test: fix race condition in oc_test.go
  spanner/oc_test.go
Labels: cla: yes

#2836 fix(profiler): do not collect disabled profile types
  profiler/profiler.go
  profiler/profiler_test.go
Labels: api: cloudprofiler, cla: yes

#2856 chore(.github): update CODEOWNER for Data Analytics clients
  .github/CODEOWNERS
Labels: automerge, cla: yes

#2851 fix(spanner/spansql): fix parsing of adjacent inline and leading comments
  spanner/spansql/parser.go
  spanner/spansql/parser_test.go
Labels: api: spanner, cla: yes

#2854 feat(godocfx): create Go DocFX YAML generator
  internal/godocfx/.gitignore
  internal/godocfx/README.md
  internal/godocfx/go.mod
  internal/godocfx/go.sum
  internal/godocfx/godocfx_test.go
  internal/godocfx/main.go
  internal/godocfx/parse.go
  internal/kokoro/publish_docs.sh
  internal/kokoro/vet.sh
  license_test.go
  third_party/pkgsite/LICENSE
  third_party/pkgsite/print_type.go
  third_party/pkgsite/synopsis.go
Labels: cla: yes

#2845 chore(bigtable): release v1.6.0
  bigtable/CHANGES.md
  internal/version/version.go
Labels: api: bigtable, cla: yes

#2860 test(storage): update post policy v4 conformance
  storage/conformance_test.go
  storage/internal/test/conformance/v4_signatures.json
Labels: cla: yes

#2861 fix(internal/kokoro): install the right version of docuploader
  internal/kokoro/publish_docs.sh
Labels: automerge, cla: yes

#2844 doc(storage): clarify ObjectIterator error case
  storage/bucket.go
  storage/doc.go
Labels: api: storage, automerge, cla: yes

#2862 fix(internal/kokoro): remove extra dash in doc tarball
  internal/kokoro/publish_docs.sh
Labels: automerge, cla: yes

#2865 chore: update dataproc CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#2872 chore(datastore): release datastore/v1.3.0
  datastore/CHANGES.md
  internal/version/version.go
Labels: cla: yes

#2873 test(storage): copy latest conformance test fixes
  storage/conformance_test.go
  storage/internal/test/conformance/v4_signatures.json
Labels: automerge, cla: yes

#2880 fix(godocfx): shorten function names
  internal/godocfx/parse.go
Labels: cla: yes

#2875 feat(dialogflow/cx): start generating apiv3beta1
  dialogflow/cx/apiv3beta1/agents_client.go
  dialogflow/cx/apiv3beta1/agents_client_example_test.go
  dialogflow/cx/apiv3beta1/doc.go
  dialogflow/cx/apiv3beta1/entity_types_client.go
  dialogflow/cx/apiv3beta1/entity_types_client_example_test.go
  dialogflow/cx/apiv3beta1/environments_client.go
  dialogflow/cx/apiv3beta1/environments_client_example_test.go
  dialogflow/cx/apiv3beta1/flows_client.go
  dialogflow/cx/apiv3beta1/flows_client_example_test.go
  dialogflow/cx/apiv3beta1/intents_client.go
  dialogflow/cx/apiv3beta1/intents_client_example_test.go
  dialogflow/cx/apiv3beta1/pages_client.go
  dialogflow/cx/apiv3beta1/pages_client_example_test.go
  dialogflow/cx/apiv3beta1/session_entity_types_client.go
  dialogflow/cx/apiv3beta1/session_entity_types_client_example_test.go
  dialogflow/cx/apiv3beta1/sessions_client.go
  dialogflow/cx/apiv3beta1/sessions_client_example_test.go
  dialogflow/cx/apiv3beta1/transition_route_groups_client.go
  dialogflow/cx/apiv3beta1/transition_route_groups_client_example_test.go
  dialogflow/cx/apiv3beta1/versions_client.go
  dialogflow/cx/apiv3beta1/versions_client_example_test.go
  dialogflow/cx/apiv3beta1/webhooks_client.go
  dialogflow/cx/apiv3beta1/webhooks_client_example_test.go
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: api: dialogflow, automerge, cla: yes

#2769 fix(storage): add content type, disposition and encoding in v4 storage post policy
  storage/conformance_test.go
  storage/post_policy_v4.go
Labels: api: storage, automerge, cla: yes

#2881 test(godocfx): add golden test
  internal/godocfx/.gitignore
  internal/godocfx/README.md
  internal/godocfx/godocfx_test.go
  internal/godocfx/main.go
  internal/godocfx/testdata/golden/index.yml
  internal/godocfx/testdata/golden/toc.yml
Labels: automerge, cla: yes

#2878 fix(datastore): increase deferred key iter limit
  datastore/datastore.go
Labels: api: datastore, automerge, cla: yes

#2885 docs(spanner): document NULL value
  spanner/value.go
  spanner/value_test.go
Labels: cla: yes

#2888 chore(spanner/spansql): restructure FROM, TABLESAMPLE
  spanner/spannertest/db_query.go
  spanner/spansql/parser.go
  spanner/spansql/parser_test.go
  spanner/spansql/sql.go
  spanner/spansql/sql_test.go
  spanner/spansql/types.go
Labels: cla: yes

#2889 chore(spanner/spansql): use ID type for identifiers throughout
  spanner/spannertest/db.go
  spanner/spannertest/db_eval.go
  spanner/spannertest/db_query.go
  spanner/spannertest/db_test.go
  spanner/spannertest/inmem.go
  spanner/spansql/parser.go
  spanner/spansql/parser_test.go
  spanner/spansql/sql.go
  spanner/spansql/sql_test.go
  spanner/spansql/types.go
Labels: api: spanner, automerge, cla: yes

#2884 feat(docfx): add support for examples
  internal/godocfx/parse.go
  internal/godocfx/testdata/golden/index.yml
Labels: automerge, cla: yes

#2866 feat(assuredworkloads): start generating apiv1beta1
  assuredworkloads/apiv1beta1/assured_workloads_client.go
  assuredworkloads/apiv1beta1/assured_workloads_client_example_test.go
  assuredworkloads/apiv1beta1/doc.go
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: automerge, cla: yes

#2887 fix(storage): complete fix for PostPolicy fields
  storage/integration_test.go
  storage/post_policy_v4.go
Labels: api: storage, automerge, cla: yes

#2890 docs: publish docs during releases
  RELEASING.md
Labels: automerge, cla: yes

#2871 feat(talent): start generating apiv4
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  talent/apiv4/company_client.go
  talent/apiv4/company_client_example_test.go
  talent/apiv4/completion_client.go
  talent/apiv4/completion_client_example_test.go
  talent/apiv4/doc.go
  talent/apiv4/event_client.go
  talent/apiv4/event_client_example_test.go
  talent/apiv4/job_client.go
  talent/apiv4/job_client_example_test.go
  talent/apiv4/tenant_client.go
  talent/apiv4/tenant_client_example_test.go
Labels: automerge, cla: yes

#2892 fix(translate): properly name examples
  translate/examples_test.go
Labels: automerge, cla: yes

#2804 feat(datastore): add opencensus tracing/stats support
  datastore/client.go
  datastore/transaction.go
Labels: api: datastore, automerge, cla: yes

#2858 feat(bigquery): add additional time partitioning intervals
  bigquery/load_test.go
  bigquery/table.go
Labels: api: bigquery, cla: yes

#2870 docs(bigquery): fix several godoc typos
  bigquery/doc.go
  bigquery/schema.go
  bigquery/table.go
Labels: api: bigquery, cla: yes

#2560 feat(bigquery): add support for optimized query path
  bigquery/bigquery.go
  bigquery/iterator.go
  bigquery/query.go
  bigquery/query_test.go
Labels: cla: yes

#2867 fix(pubsub): check both client errors on Close
  pubsub/go.sum
  pubsub/pubsub.go
  pubsub/streaming_pull_test.go
Labels: api: pubsub, cla: yes

#2894 fix(godocfx): filter out other modules, sort pkgs
  internal/godocfx/go.sum
  internal/godocfx/parse.go
Labels: automerge, cla: yes

#2902 chore(bigquery): release bigquery/v1.11.0
  bigquery/CHANGES.md
  internal/version/version.go
Labels: cla: yes

#2903 docs: clear up publish_docs docs
  RELEASING.md
Labels: automerge, cla: yes

#2901 fix(pubsub/pstest): add missing support for filter and retry policy
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
Labels: cla: yes

#2904 chore(pubsub): release pubsub/v1.6.2
  pubsub/CHANGES.md
Labels: cla: yes

#2895 fix(storage): encode + in SignedURL query params
  storage/conformance_test.go
  storage/storage.go
Labels: api: storage, automerge, cla: yes

#2907 chore(storage): release storage/v1.12.0
  internal/version/version.go
  storage/CHANGES.md
Labels: cla: yes

#2909 test(spanner/spansql): add fuzz target for ParseQuery
  spanner/spansql/fuzz.go
Labels: api: spanner, automerge, cla: yes

#2896 feat(spanner/spansql): parse joins
  spanner/spansql/parser.go
  spanner/spansql/parser_test.go
  spanner/spansql/sql.go
  spanner/spansql/types.go
Labels: api: spanner, automerge, cla: yes

#2917 chore(godocfx): mark methods as methods
  internal/godocfx/parse.go
  internal/godocfx/testdata/golden/index.yml
Labels: cla: yes

#2916 feat(pubsub/pstest): Add reactor options to pstest server
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
Labels: cla: yes

#2922 chore(pubsub): release pubsub/v1.7.0
  internal/version/version.go
  pubsub/CHANGES.md
Labels: cla: yes

#2926 feat(pubsub/pstest)!: Add status code to error injection.
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
Labels: cla: yes

#2924 feat(spanner/spansql): parse path expressions
  spanner/spansql/parser.go
  spanner/spansql/parser_test.go
  spanner/spansql/sql.go
  spanner/spansql/types.go
Labels: api: spanner, automerge, cla: yes

#2931 feat(spanner/spannertest): evaluate path expressions
  spanner/spannertest/README.md
  spanner/spannertest/db.go
  spanner/spannertest/db_eval.go
  spanner/spannertest/db_query.go
  spanner/spannertest/db_test.go
Labels: api: spanner, automerge, cla: yes

#2927 feat(godocfx): include README in output
  internal/godocfx/godocfx_test.go
  internal/godocfx/main.go
  internal/godocfx/parse.go
  internal/godocfx/testdata/golden/README.md
  internal/godocfx/testdata/golden/toc.yml
Labels: automerge, cla: yes

#2928 chore(pubsub): release pubsub/v1.8.0
  internal/version/version.go
  pubsub/CHANGES.md
Labels: api: pubsub, cla: yes

#2921 docs(all): add a testing.md
  testing.md
Labels: automerge, cla: yes

#2906 chore(all): replace un-inclusive language
  datastore/datastore.go
  spanner/read.go
  spanner/spansql/sql_test.go
Labels: automerge, cla: yes

#2938 chore(internal): change docs staging bucket to prod
  internal/kokoro/publish_docs.sh
Labels: automerge, cla: yes

#2940 fix(bigquery): address issue with directly Read()'ing from a Query
  bigquery/integration_test.go
  bigquery/query.go
Labels: cla: yes

#2941 chore: release bigquery/v1.11.1
  bigquery/CHANGES.md
  internal/version/version.go
Labels: cla: yes
