Repository googleapis/google-cloud-go, pull requests merged in 2020-07, with the labels that each got.

#2543 spanner: release v1.7.0
  internal/version/version.go
  spanner/CHANGES.md
Labels: api: spanner, cla: yes

#2545 spanner: add a statement-based way to run read-write transaction.
  spanner/examples_test.go
  spanner/integration_test.go
  spanner/retry.go
  spanner/retry_test.go
  spanner/transaction.go
  spanner/transaction_test.go
Labels: api: spanner, cla: yes

#2555 chore(pubsub): release v1.5.0
  internal/version/version.go
  pubsub/CHANGES.md
Labels: cla: yes

#2558 pubsub/pstest: fake time function
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
Labels: api: pubsub, cla: yes, type: feature request

#2513 spanner: remove appengine-specific numChannels.
  spanner/appengine.go
  spanner/client.go
  spanner/not_appengine.go
Labels: api: spanner, cla: yes

#2554 chore(internal/gapicgen): start generating policytroubleshooter apiv1
  internal/gapicgen/generator/config.go
Labels: automerge, cla: yes

#2559 test(spanner): log warning instead of fail for stress test
  spanner/session_test.go
Labels: cla: yes

#2567 fix(internal/kokoro): remove install of staticcheck
  internal/kokoro/vet.sh
Labels: automerge, cla: yes

#2568 chore(internal/gapicgen): start generating dashboard apiv1
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  monitoring/dashboard/apiv1/dashboards_client.go
  monitoring/dashboard/apiv1/dashboards_client_example_test.go
  monitoring/dashboard/apiv1/doc.go
Labels: automerge, cla: yes

#2569 feat(policytroubleshooter): start generating apiv1
  policytroubleshooter/apiv1/doc.go
  policytroubleshooter/apiv1/iam_checker_client.go
  policytroubleshooter/apiv1/iam_checker_client_example_test.go
Labels: cla: yes

#2564 chore(all): update all deps
  bigquery/go.mod
  bigquery/go.sum
  bigtable/go.mod
  bigtable/go.sum
  datastore/go.mod
  datastore/go.sum
  firestore/go.mod
  firestore/go.sum
  go.mod
  go.sum
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
  logging/go.mod
  logging/go.sum
  pubsub/go.mod
  pubsub/go.sum
  spanner/go.mod
  spanner/go.sum
  storage/go.mod
  storage/go.sum
Labels: automerge, cla: yes

#2521 Profiler: change to disable OpenCensus Telemetry by default
  profiler/profiler.go
Labels: cla: yes

#2573 chore(.github): automate dependency updates with Renovate
  .github/renovate.json
Labels: automerge, cla: yes

#2577 fix(spanner): add extra field to ignore with cmp
  spanner/cmp_test.go
Labels: cla: yes

#2580 spanner: fix the required resource prefix.
  spanner/batch.go
  spanner/pdml.go
  spanner/session.go
  spanner/transaction.go
Labels: api: spanner, cla: yes

#2581 spanner: do not copy protobuf messages by value.
  spanner/batch.go
Labels: api: spanner, cla: yes

#2583 fix(spanner): add extra field to ignore with cmp and use testEqual
  spanner/cmp_test.go
  spanner/transaction_test.go
Labels: api: spanner, cla: yes

#2585 bigquery: address cached reference in rowiterator
  bigquery/iterator.go
Labels: cla: yes

#2576 chore(all): release v0.61.0
  CHANGES.md
Labels: automerge, cla: yes

#2414 test(spanner): cleanup mockserver and mockclient
  spanner/internal/testutil/inmem_spanner_server.go
  spanner/internal/testutil/mockclient.go
  spanner/internal/testutil/mockserver.go
  spanner/read_test.go
Labels: api: spanner, cla: yes

#2602 feat(functions): start generating apiv1
  functions/apiv1/cloud_functions_client.go
  functions/apiv1/cloud_functions_client_example_test.go
  functions/apiv1/doc.go
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: cla: yes

#2597 test(spanner): fix failed TestRsdBlockingStates test
  spanner/internal/testutil/inmem_spanner_server.go
  spanner/read_test.go
Labels: api: spanner, cla: yes

#2588 feat(profiler): update proftest to support parsing floating-point backoff durations
  profiler/proftest/proftest.go
  profiler/proftest/proftest_test.go
Labels: automerge, cla: yes

#2605 fix(spanner): add the missing resource prefix
  spanner/batch.go
  spanner/transaction.go
Labels: api: spanner, cla: yes

#2608 docs(spanner): clarify parameter naming requirements
  spanner/statement.go
Labels: api: spanner, cla: yes

#2609 fix(spanner): set 'gccl' to the request header.
  spanner/client_test.go
  spanner/sessionclient.go
Labels: api: spanner, cla: yes

#2599 feat(spanner): support of client-level custom retry settings
  spanner/client.go
  spanner/client_test.go
  spanner/sessionclient.go
  spanner/sessionclient_test.go
Labels: api: spanner, cla: yes

#2616 feat(billing/budgets): generate apiv1beta1
  billing/budgets/apiv1beta1/budget_client.go
  billing/budgets/apiv1beta1/budget_client_example_test.go
  billing/budgets/apiv1beta1/doc.go
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: automerge, cla: yes

#2524 bigtable: implement managed backup feature
  bigtable/admin.go
  bigtable/integration_test.go
Labels: cla: yes

#2618 bigqueryNullFloat64 add +Inf, -Inf and NaN support
  bigquery/nulls.go
  bigquery/nulls_test.go
Labels: automerge, cla: yes

#2620 chore(spanner): release v1.8.0
  internal/version/version.go
  spanner/CHANGES.md
Labels: api: spanner, cla: yes

#2623 chore(bigtable): release v1.5.0
  bigtable/CHANGES.md
Labels: automerge, cla: yes

#2619 docs: update CONTRIBUTING.md with some PR setup info
  CONTRIBUTING.md
Labels: automerge, cla: yes

#2624 fix(pubsub): use grpc conn pool option for subscriber client
  pubsub/pubsub.go
Labels: cla: yes

#2627 chore: release pubsub/v1.6.0
  internal/version/version.go
  pubsub/CHANGES.md
Labels: cla: yes

#2626 chore: release bigquery/v1.10.0
  bigquery/CHANGES.md
Labels: cla: yes

#2563 feat(storage): add StartOffset and EndOffset to Query
  storage/bucket.go
  storage/integration_test.go
  storage/storage.go
Labels: automerge, cla: yes

#2613 fix(datastore): write nil interface as a nil property with Save()
  datastore/save.go
  datastore/save_test.go
Labels: api: datastore, automerge, cla: yes, type: bug

#2631 docs(firestore): fixed a spelling error
  firestore/watch.go
Labels: api: firestore, cla: yes

#2634 fix(internal/gapicgen): only open draft PR if there are genproto changes
  internal/gapicgen/cmd/genbot/github.go
Labels: cla: yes

#2614 feat(spanner): support custom field type
  spanner/client_test.go
  spanner/value.go
  spanner/value_test.go
Labels: api: spanner, cla: yes

#2628 fix(profiler): fix order of units in regexp used to parse backoff duration
  profiler/proftest/proftest.go
  profiler/proftest/proftest_test.go
Labels: cla: yes

#2630 fix(storage): add retry for TestIntegration_DeleteObjectInBucketWithRetentionPolicy
  storage/integration_test.go
Labels: api: storage, automerge, cla: yes, type: cleanup

#2420 feat(firestore): implement limitToLast
  firestore/integration_test.go
  firestore/query.go
  firestore/transaction.go
Labels: api: firestore, automerge, cla: yes, type: feature request

#2647 fix(pubsub): parse EnableMessageOrdering field in proto to cfg conversion
  pubsub/subscription.go
  pubsub/subscription_test.go
Labels: cla: yes

#2648 chore: release pubsub/v1.6.1
  internal/version/version.go
  pubsub/CHANGES.md
Labels: cla: yes

#2650 test(firestore): del skip in TestTransactionErrors
  firestore/transaction_test.go
Labels: api: firestore, automerge, cla: yes, type: cleanup

#2645 chore(firestore): release firestore/v1.3.0
  firestore/CHANGES.md
Labels: cla: yes

#2598 firestore, datastore: make DetectProjectID work with the emulator
  datastore/datastore.go
  firestore/client.go
Labels: cla: yes

#2655 spanner/spannertest: return error for Read with no keys
  spanner/spannertest/db.go
Labels: api: spanner, cla: yes

#2656 spanner/spansql: restructure types and parsing for column options
  spanner/spannertest/db.go
  spanner/spannertest/db_test.go
  spanner/spansql/parser.go
  spanner/spansql/parser_test.go
  spanner/spansql/sql.go
  spanner/spansql/sql_test.go
  spanner/spansql/types.go
Labels: api: spanner, cla: yes

#2511 docs(CONTRIBUTING): add guidelines about about conventional commits
  CONTRIBUTING.md
Labels: automerge, cla: yes

#2617 feat(notebooks): generate apiv1beta1
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  notebooks/apiv1beta1/doc.go
  notebooks/apiv1beta1/notebook_client.go
  notebooks/apiv1beta1/notebook_client_example_test.go
Labels: cla: yes

#2646 chore(all): release v0.62.0
  CHANGES.md
Labels: cla: yes

#2658 docs(firestore): note edge case for iterator.Done
  firestore/query.go
Labels: automerge, cla: yes

#2671 chore(profiler): remove comment indicating profiler library is experimental
  profiler/profiler.go
Labels: cla: yes
