Repository googleapis/google-cloud-go, pull requests merged in 2020-06, with the labels that each got.

#2401 all: update contirbuting information as we have moved to GitHub
  CONTRIBUTING.md
  RELEASING.md
Labels: cla: yes

#2413 .github: remove pull request template
  .github/pull_request_template.md
Labels: cla: yes

#2412 .github/ISSUE_TEMPLATE: ask for go version and go env
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: automerge, cla: yes

#2427 pubsub: prefer the word allowlist
  pubsub/integration_test.go
Labels: cla: yes

#2431 compute/metadata: pass cancelable context to DNS lookup
  compute/metadata/metadata.go
Labels: cla: yes

#2432 README.md: fix GoDoc badge source
  README.md
Labels: cla: yes

#2424 internal: refactor genbot to work with GitHub
  internal/gapicgen/cmd/genbot/Dockerfile
  internal/gapicgen/cmd/genbot/README.md
  internal/gapicgen/cmd/genbot/gapics.go
  internal/gapicgen/cmd/genbot/generate.go
  internal/gapicgen/cmd/genbot/genproto.go
  internal/gapicgen/cmd/genbot/github.go
  internal/gapicgen/cmd/genbot/main.go
  internal/gapicgen/cmd/genbot/update.go
  internal/gapicgen/cmd/genlocal/README.md
  internal/gapicgen/cmd/genlocal/main.go
  internal/gapicgen/cmd/genmgr/Dockerfile
  internal/gapicgen/cmd/genmgr/README.md
  internal/gapicgen/cmd/genmgr/main.go
  internal/gapicgen/db/db.go
  internal/gapicgen/git.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
Labels: automerge, cla: yes

#2435 internal/gapicgen: add missing license headers
  internal/gapicgen/cmd/genbot/generate.go
  internal/gapicgen/cmd/genbot/github.go
  internal/gapicgen/cmd/genbot/update.go
  internal/kokoro/continuous.sh
  internal/kokoro/genmgr.sh
  internal/kokoro/presubmit.sh
Labels: automerge, cla: yes

#2418 spanner: fix TestIntegration_StartBackupOperation test
  spanner/integration_test.go
Labels: api: spanner, cla: yes

#2411 spanner/spannertest: support MIN/MAX aggregation functions
  spanner/spannertest/db_test.go
  spanner/spannertest/funcs.go
  spanner/spansql/keywords.go
Labels: api: spanner, cla: yes

#2442 pubsub: unflake TestIntegration_All
  pubsub/integration_test.go
Labels: api: pubsub, cla: yes

#2446 all: remove reference to gerrit codereview
  README.md
Labels: cla: yes

#2448 internal/gapicgen: add more logging and fix pr status bug
  internal/gapicgen/cmd/genbot/github.go
  internal/gapicgen/cmd/genbot/main.go
Labels: cla: yes

#2444 pubsub: fix panic on Topic.ResumePublish
  pubsub/topic.go
Labels: cla: yes

#2449 all: clean up RELEASING.md
  RELEASING.md
Labels: cla: yes

#2447 Release Datastore v1.2.0
  datastore/CHANGES.md
  internal/version/version.go
Labels: cla: yes

#2440 bigquery/benchmarks: revamp benchmarks
  bigquery/benchmarks/README.md
  bigquery/benchmarks/bench.go
  bigquery/benchmarks/benchmarked-queries.json
  bigquery/benchmarks/queries.json
Labels: cla: yes

#2416 spanner: add oc tests for session pool metrics.
  spanner/go.mod
  spanner/go.sum
  spanner/oc_test.go
Labels: api: spanner, cla: yes

#2465 .github: add myself as a fallback assignee
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#2466 .github: add CODEOWNERS file
  .github/CODEOWNERS
Labels: automerge, cla: yes

#2410 pubsub: close ready channel on publish error
  pubsub/topic.go
Labels: api: pubsub, cla: yes

#2467 storage: unflake TestIntegration_ACL
  storage/integration_test.go
Labels: cla: yes

#2455 pubsub/pstest: add support for ordering key
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
Labels: cla: yes

#2468 mod: update google.golang.org/api to v0.27.0
  bigquery/go.mod
  bigquery/go.sum
  bigtable/go.mod
  bigtable/go.sum
  datastore/go.mod
  datastore/go.sum
  firestore/go.mod
  firestore/go.sum
  go.mod
  go.sum
  logging/go.mod
  logging/go.sum
  pubsub/go.mod
  pubsub/go.sum
  spanner/go.mod
  spanner/go.sum
  storage/go.mod
  storage/go.sum
Labels: automerge, cla: yes

#2459 internal/gapicgen: check if google-cloud-go opened and merged a PR
  internal/gapicgen/cmd/genbot/main.go
Labels: automerge, cla: yes

#2454 storage: update docs on ChunkSize and retries
  storage/writer.go
Labels: automerge, cla: yes

#2475 internal/gapicgen: use draft PRs for google-cloud-go
  internal/gapicgen/cmd/genbot/github.go
  internal/gapicgen/cmd/genbot/update.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
Labels: cla: yes

#2479 spanner/spannertest: fix evaluation on IN
  spanner/spannertest/db_eval.go
  spanner/spannertest/db_test.go
Labels: api: spanner, cla: yes

#2482 compute/metadata: Fix detecting metadata server
  compute/metadata/metadata.go
Labels: cla: yes

#2474 pubsub: add support for detach subscription
  pubsub/integration_test.go
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
  pubsub/subscription.go
  pubsub/topic.go
  pubsub/topic_test.go
Labels: api: pubsub, cla: yes, type: feature request

#2487 .github: remove myself as fallback in blunderbuss
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#2485 storage: release v1.10.0
  internal/version/version.go
  storage/CHANGES.md
Labels: cla: yes

#2490 storage: remove retry for write integration test
  storage/integration_test.go
Labels: cla: yes

#2494 spanner: unskip tests for emulator 0.8.0.
  spanner/emulator_test.sh
  spanner/integration_test.go
Labels: api: spanner, cla: yes

#2460 spanner: only retry certain types of internal errors.
  spanner/client_test.go
  spanner/read.go
  spanner/retry.go
Labels: api: spanner, cla: yes, type: bug

#2500 internal: start generating asset v1p5beta1
  internal/gapicgen/generator/config.go
Labels: cla: yes

#2489 internal/gapicgen: bump surfaces to GA
  internal/gapicgen/generator/config.go
Labels: automerge, cla: yes

#2491 internal/gapicgen: support generating a single gapic in genlocal
  internal/gapicgen/cmd/genbot/generate.go
  internal/gapicgen/cmd/genlocal/main.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/generator/generator.go
Labels: automerge, cla: yes

#2502 gh-pages: remove and redirect to API reference page
  assets/images/icon-lang-go-godoc.ico
  home.html
  index.html
  manifest.json
  src/app-4aaf1b49f3.css
  src/app-8d3af8a180.js
  src/images/icon-dropdown.svg
  src/images/icon-lang-cpp.svg
  src/images/icon-lang-dotnet.svg
  src/images/icon-lang-go-godoc.ico
  src/images/icon-lang-go.svg
  src/images/icon-lang-java.svg
  src/images/icon-lang-node-cta.svg
  src/images/icon-lang-node.svg
  src/images/icon-lang-php-gray.svg
  src/images/icon-lang-php.svg
  src/images/icon-lang-python-gray.svg
  src/images/icon-lang-python.svg
  src/images/icon-lang-ruby-gray.svg
  src/images/icon-lang-ruby.svg
  src/images/icon-link-github.svg
  src/images/icon-link-issues.svg
  src/images/icon-link-package-manager.svg
  src/images/icon-link-rubygems.svg
  src/images/icon-link-stackoverflow.svg
  src/images/icon-menu.svg
  src/images/lang-bg.png
  src/images/logo-full.svg
  src/images/logo.svg
  src/vendor-7562b190aa.js
  src/vendor-d362a4bbd8.css
Labels: cla: yes

#2496 all: remove dependency on honnef.co/go/tools
  go.mod
  tools.go
Labels: cla: yes

#2505 all: release v0.59.0
  CHANGES.md
Labels: cla: yes

#2506 all: update sub-modules to cloud.google.com/go v0.59.0
  bigquery/go.mod
  bigquery/go.sum
  bigtable/go.mod
  bigtable/go.sum
  datastore/go.mod
  datastore/go.sum
  firestore/go.mod
  firestore/go.sum
  logging/go.mod
  logging/go.sum
  pubsub/go.mod
  pubsub/go.sum
  spanner/go.mod
  spanner/go.sum
  storage/go.mod
  storage/go.sum
Labels: cla: yes

#2488 internal/gapicgen: start generating gaming apiv1beta
  internal/gapicgen/generator/config.go
Labels: automerge, cla: yes

#2509 test(spanner): return err from tx
  spanner/integration_test.go
Labels: cla: yes

#2514 fix(internal/gapicgen): make PR search more specific
  internal/gapicgen/cmd/genbot/github.go
Labels: cla: yes

#2510 refactor(internal/gapicgen): rename commit titles for regen
  internal/gapicgen/cmd/genbot/github.go
Labels: automerge, cla: yes

#2507 refactor(all): refactor examples to reduce dependency tree
  examples_test.go
  go.mod
  go.sum
Labels: cla: yes

#2516 bigquery: support type aliases in SchemaFromJSON
  bigquery/schema.go
  bigquery/schema_test.go
Labels: cla: yes

#2531 irm: remove apiv1alpha2 client
  internal/gapicgen/generator/config.go
  irm/apiv1alpha2/doc.go
  irm/apiv1alpha2/incident_client.go
  irm/apiv1alpha2/incident_client_example_test.go
  irm/apiv1alpha2/mock_test.go
Labels: cla: yes

#2477 bigtable: add support for instance state and labels
  bigtable/admin.go
  bigtable/integration_test.go
Labels: automerge, cla: yes

#2518 chore(all): release v0.60.0
  CHANGES.md
Labels: cla: yes

#2532 chore(all): update to cloud.google.com/go v0.60.0
  bigquery/go.mod
  bigquery/go.sum
  bigtable/go.mod
  bigtable/go.sum
  datastore/go.mod
  datastore/go.sum
  firestore/go.mod
  firestore/go.sum
  logging/go.mod
  logging/go.sum
  pubsub/go.mod
  pubsub/go.sum
  spanner/go.mod
  spanner/go.sum
  storage/go.mod
  storage/go.sum
Labels: automerge, cla: yes

#2533 bigquery: release bigquery/v1.9.0
  bigquery/CHANGES.md
  internal/version/version.go
Labels: cla: yes

#2520 spanner: never sample `ping()` trace spans
  spanner/session.go
Labels: api: spanner, cla: yes

#2529 fix(spanner): allow encoding struct with custom types to mutation
  spanner/client_test.go
  spanner/statement_test.go
  spanner/value.go
Labels: cla: yes

#2522 pubsub: Add support for server-side flow control
  pubsub/iterator.go
  pubsub/pullstream.go
  pubsub/pullstream_test.go
  pubsub/subscription.go
Labels: cla: yes

#2536 bigtable: release v1.4.0
  bigtable/CHANGES.md
Labels: cla: yes

#2484 bigquery: refactor RowIterator to support fast query path
  bigquery/integration_test.go
  bigquery/iterator.go
  bigquery/iterator_test.go
  bigquery/job.go
  bigquery/read_test.go
  bigquery/table.go
Labels: automerge, cla: yes

#2526 spanner: cleanup backoff files and rename a variable
  spanner/client.go
  spanner/internal/backoff/backoff.go
  spanner/internal/backoff/backoff_test.go
Labels: api: spanner, cla: yes

#2539 spanner: fix TestClient_WithGRPCConnectionPoolAndNumChannels_Misconfigured test
  spanner/client_test.go
Labels: api: spanner, cla: yes
