Repository googleapis/google-cloud-go, pull requests merged in 2020-08, with the labels that each got.

#2676 test(storage): re-enable skipped write retry test
  storage/writer_test.go
Labels: automerge, cla: yes

#2675 test(spanner): unskip tests for emulator
  spanner/integration_test.go
Labels: api: spanner, cla: yes

#2679 test(storage): unskip SignedURL_WithEncryptionKeys
  storage/integration_test.go
Labels: automerge, cla: yes

#2670 feat(analytics/admin): start generating apiv1alpha
  analytics/admin/apiv1alpha/analytics_admin_client.go
  analytics/admin/apiv1alpha/analytics_admin_client_example_test.go
  analytics/admin/apiv1alpha/doc.go
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: automerge, cla: yes

#2669 feat(functions/metadata): Special-case marshaling
  functions/metadata/metadata.go
  functions/metadata/metadata_test.go
Labels: automerge, cla: yes

#2681 feat(gaming): start generate apiv1
  gaming/apiv1/doc.go
  gaming/apiv1/game_server_clusters_client.go
  gaming/apiv1/game_server_clusters_client_example_test.go
  gaming/apiv1/game_server_configs_client.go
  gaming/apiv1/game_server_configs_client_example_test.go
  gaming/apiv1/game_server_deployments_client.go
  gaming/apiv1/game_server_deployments_client_example_test.go
  gaming/apiv1/realms_client.go
  gaming/apiv1/realms_client_example_test.go
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: automerge, cla: yes

#2678 fix(spanner): update pdml to retry EOS internal error
  spanner/pdml.go
  spanner/pdml_test.go
Labels: api: spanner, cla: yes

#2683 chore(profiler): replace references to "Stackdriver Profiler" with "Cloud Profiler"
  profiler/profiler.go
Labels: automerge, cla: yes

#2684 chore(internal/gapicgen): generate profiler metadata
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/gapics.go
Labels: automerge, cla: yes

#2637 feat(internal/kokoro): add script to test compatibility with samples
  internal/kokoro/build_samples.sh
Labels: cla: yes

#2687 test(storage): unskip UpdateRetentionPolicy test
  storage/integration_test.go
Labels: cla: yes

#2677 chore(profiler): add Kokoro configuration for profiler's long-running backoff test
  profiler/integration_test.go
  profiler/kokoro/continuous_backoff.cfg
  profiler/kokoro/integration_test.sh
Labels: cla: yes

#2692 chore(profiler): fix Kokoro configurations
  profiler/kokoro/continuous_backoff.cfg
Labels: cla: yes

#2693 chore(profiler): increase timeout for profiler backoff test to 1 hour
  profiler/kokoro/integration_test.sh
Labels: cla: yes

#2690 chore(internal/gapicgen): remove gerrit ref
  internal/gapicgen/cmd/genbot/README.md
Labels: automerge, cla: yes

#2689 chore(all): release v0.63.0
  CHANGES.md
Labels: cla: yes

#2700 feat(pubsublite): start generating v1
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  pubsublite/apiv1/admin_client.go
  pubsublite/apiv1/admin_client_example_test.go
  pubsublite/apiv1/cursor_client.go
  pubsublite/apiv1/cursor_client_example_test.go
  pubsublite/apiv1/doc.go
  pubsublite/apiv1/partition_assignment_client.go
  pubsublite/apiv1/partition_assignment_client_example_test.go
  pubsublite/apiv1/publisher_client.go
  pubsublite/apiv1/publisher_client_example_test.go
  pubsublite/apiv1/subscriber_client.go
  pubsublite/apiv1/subscriber_client_example_test.go
  pubsublite/apiv1/topic_stats_client.go
  pubsublite/apiv1/topic_stats_client_example_test.go
Labels: cla: yes

#2703 test(speech): skip tests that rely on deleted bucket
  speech/apiv1/Recognize_smoke_test.go
  speech/apiv1p1beta1/Recognize_smoke_test.go
Labels: cla: yes

#2704 test(speech): reference new bucket for audio file
  speech/apiv1/Recognize_smoke_test.go
  speech/apiv1p1beta1/Recognize_smoke_test.go
Labels: automerge, cla: yes

#2701 fix(spanner): specify credentials with SPANNER_EMULATOR_HOST
  spanner/client.go
  spanner/client_test.go
Labels: api: spanner, cla: yes

#2712 chore(internal/gapicgen): stop frozen APIs from even generating
  internal/gapicgen/generator/genproto.go
Labels: cla: yes

#2715 chore(internal/gapicgen): update gapic gen version
  internal/gapicgen/cmd/genbot/Dockerfile
Labels: cla: yes

#2721 chore(internal/gapicgen): fix genbot
  internal/gapicgen/cmd/genbot/Dockerfile
Labels: automerge, cla: yes

#2665 feat(bigtable): implement LabelFilter
  bigtable/filter.go
  bigtable/integration_test.go
  bigtable/reader.go
  bigtable/reader_test.go
Labels: api: bigtable, cla: yes, type: feature request

#2716 chore(.github): add release please config for root module
  .github/release-please.yml
Labels: cla: yes

#2724 fix(spanner): retry session not found for read
  spanner/client_test.go
  spanner/internal/testutil/inmem_spanner_server.go
  spanner/transaction.go
Labels: cla: yes

#2728 fix(spanner): call ctx.cancel after stats have been recorded
  spanner/session.go
Labels: cla: yes

#2733 chore(spanner): release v1.9.0
  internal/version/version.go
  spanner/CHANGES.md
Labels: api: spanner, cla: yes

#2742 chore(all): remove reviewer
  .github/CODEOWNERS
Labels: cla: yes

#2743 build: configure alternate CHANGELOG path
  .github/release-please.yml
Labels: automerge, cla: yes

#2752 doc(storage): storage.Client should be reused
  storage/doc.go
  storage/storage.go
Labels: automerge, cla: yes

#2632 feat(pubsub/pstest): allow updating subscription dead letter policies
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
Labels: cla: yes

#2748 feat(spanner): add custom type support to spanner.Key
  spanner/key.go
  spanner/key_test.go
Labels: automerge, cla: yes

#2756 fix(all): correct minor typos
  bigquery/job.go
  profiler/integration_test.go
  profiler/proftest/proftest.go
Labels: cla: yes

#2736 fix(spanner): update PDML to take sessions from pool
  spanner/pdml.go
  spanner/pdml_test.go
Labels: api: spanner, cla: yes

#2738 docs(storage): Fix the documentation link
  storage/storage.go
Labels: automerge, cla: yes

#2762 chore(internal/gapicgen): have genbot fallback to env vars
  internal/gapicgen/cmd/genbot/Dockerfile
  internal/gapicgen/cmd/genbot/README.md
  internal/gapicgen/cmd/genbot/github.go
  internal/gapicgen/cmd/genbot/main.go
Labels: cla: yes

#2512 feat(storage): add new OLM conditions
  storage/bucket.go
  storage/bucket_test.go
  storage/integration_test.go
  storage/storage.go
  storage/storage_test.go
Labels: cla: yes

#2663 feat(logging): adding missing fields to httpRequest
  logging/logging.go
Labels: api: logging, cla: yes

#2782 feat(storage): allow CustomTime to be updated
  storage/integration_test.go
  storage/storage.go
Labels: api: storage, cla: yes

#2786 chore(internal/gapicgen): update microgen to v0.15.1
  internal/gapicgen/cmd/genbot/Dockerfile
Labels: cla: yes

#2787 chore(logging): releasing v1.1.0
  internal/version/version.go
  logging/CHANGES.md
Labels: cla: yes

#2785 chore(storage): release v1.11.0
  storage/CHANGES.md
Labels: cla: yes

#2777 fix(bigquery): address issue with returntype for routines
  bigquery/integration_test.go
  bigquery/routine.go
  bigquery/routine_test.go
Labels: api: bigquery, cla: yes

#2790 chore(all): update version information to 1.15
  CONTRIBUTING.md
  README.md
  internal/gapicgen/cmd/genbot/Dockerfile
  internal/kokoro/vet.sh
Labels: automerge, cla: yes

#2739 chore: update pkg doc on timeouts
  doc.go
Labels: cla: yes

#2796 feat(analytics/data): start generating apiv1alpha
  analytics/data/apiv1alpha/alpha_analytics_data_client.go
  analytics/data/apiv1alpha/alpha_analytics_data_client_example_test.go
  analytics/data/apiv1alpha/doc.go
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: automerge, cla: yes

#2797 feat(video/transcoder): start generating apiv1beta1
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  video/transcoder/apiv1beta1/doc.go
  video/transcoder/apiv1beta1/transcoder_client.go
  video/transcoder/apiv1beta1/transcoder_client_example_test.go
Labels: automerge, cla: yes

#2799 feat(workflows): start generating apiv1beta
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  workflows/apiv1beta/doc.go
  workflows/apiv1beta/workflows_client.go
  workflows/apiv1beta/workflows_client_example_test.go
Labels: automerge, cla: yes

#2800 feat(workflows/executions): start generating apiv1beta
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  workflows/executions/apiv1beta/doc.go
  workflows/executions/apiv1beta/executions_client.go
  workflows/executions/apiv1beta/executions_client_example_test.go
Labels: automerge, cla: yes
