Repository googleapis/google-cloud-go, pull requests merged in 2021-03, with the labels that each got.

#3754 test(profiler): properly retry gimme installation
  profiler/integration_test.go
Labels: api: cloudprofiler, cla: yes

#3730 chore(storage): release v1.15.0
  storage/CHANGES.md
Labels: api: storage, cla: yes

#3759 fix(tables): use area120tables_v1alpha1.yaml as api-service-config
  internal/gapicgen/generator/config.go
Labels: automerge, cla: yes

#3761 chore(internal/kokoro): enable apidiff
  internal/kokoro/check_incompat_changes.sh
Labels: cla: yes

#3760 feat(bigquery): support type alias names for numeric/bignumeric schemas
  bigquery/schema.go
  bigquery/schema_test.go
Labels: api: bigquery, cla: yes

#3767 feat(internal/godocfx): keep some cross links on same domain
  internal/godocfx/godocfx_test.go
  internal/godocfx/parse.go
  internal/godocfx/testdata/golden/index.yml
Labels: automerge, cla: yes

#3768 fix(internal/godocfx): prevent index out of bounds when pkg == mod
  internal/godocfx/parse.go
Labels: automerge, cla: yes

#3770 chore(internal/gapicgen): remove manual trace from manifest
  internal/gapicgen/generator/gapics.go
Labels: cla: yes

#3752 fix(pubsub): hide context.Cancelled error in sync pull
  pubsub/iterator.go
  pubsub/iterator_test.go
Labels: cla: yes

#3774 docs(pubsublite): specify ranges for TopicConfigToUpdate values
  pubsublite/config.go
Labels: api: pubsublite, cla: yes

#3777 feat(internal): add ability to regenerate one module's docs
  internal/kokoro/publish_docs.sh
Labels: cla: yes

#3779 fix(internal): fix Bash syntax
  internal/kokoro/publish_docs.sh
Labels: automerge, cla: yes

#3780 fix(pubsub): update quiescenceDur in failing e2e test
  pubsub/internal/longtest/endtoend_test.go
Labels: api: pubsub, cla: yes

#3788 feat(metastore): start generating apiv1beta
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  metastore/apiv1beta/dataproc_metastore_client.go
  metastore/apiv1beta/dataproc_metastore_client_example_test.go
  metastore/apiv1beta/doc.go
  metastore/apiv1beta/gapic_metadata.json
Labels: api: metastore, automerge, cla: yes

#3794 chore(internal/kokoro): remove apidiff export data
  internal/kokoro/check_incompat_changes.sh
  pubsub/pkg.master
Labels: cla: yes

#3793 refactor(pubsub): update proto library dependency for linter
  pubsub/apiv1/mock_test.go
  pubsub/go.mod
  pubsub/integration_test.go
  pubsub/iterator.go
  pubsub/loadtest/loadtest.go
  pubsub/message.go
  pubsub/mock_test.go
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
  pubsub/pullstream.go
  pubsub/snapshot.go
  pubsub/streaming_pull_test.go
  pubsub/subscription.go
  pubsub/subscription_test.go
  pubsub/topic.go
Labels: api: pubsub, cla: yes

#3806 test(storage): fix unauthenticated access tests
  storage/integration_test.go
Labels: api: storage, cla: yes

#3808 chore(internal/godocfx): don't include READMEs
  internal/godocfx/main.go
Labels: automerge, cla: yes

#3799 test(pubsublite): fix flaky TestAssignerHandlePartitionFailure
  pubsublite/internal/wire/assigner_test.go
Labels: api: pubsublite, automerge, cla: yes

#3816 feat(internal/godocfx): handle Markdown content
  header_test.go
  internal/godocfx/go.mod
  internal/godocfx/go.sum
  internal/godocfx/parse.go
  internal/godocfx/testdata/golden/index.yml
  internal/kokoro/vet.sh
  third_party/go/doc/Makefile
  third_party/go/doc/comment.go
  third_party/go/doc/comment_test.go
  third_party/go/doc/doc.go
  third_party/go/doc/example.go
  third_party/go/doc/example_test.go
  third_party/go/doc/exports.go
  third_party/go/doc/filter.go
  third_party/go/doc/headscan.go
  third_party/go/doc/reader.go
  third_party/go/doc/synopsis.go
  third_party/go/doc/synopsis_test.go
  third_party/pkgsite/print_type.go
Labels: automerge, cla: yes

#3821 fix(pubsublite): increase default timeouts for publish and subscribe stream connections
  pubsublite/internal/wire/settings.go
  pubsublite/pscompat/settings.go
Labels: api: pubsublite, cla: yes

#3819 feat(internal/godocfx): add prettyprint class to code blocks
  internal/godocfx/goldmark-codeblock/codeblock.go
  internal/godocfx/parse.go
  internal/godocfx/testdata/golden/index.yml
Labels: automerge, cla: yes

#3769 chore(internal/kokoro): port check_incompat_changes
  internal/apidiff/apidiff.go
  internal/kokoro/check_incompat_changes.sh
Labels: cla: yes

#3810 fix(pubsublite): fix committer races
  pubsublite/internal/wire/committer.go
  pubsublite/internal/wire/committer_test.go
  pubsublite/internal/wire/subscriber_test.go
Labels: api: pubsublite, cla: yes

#3776 fix(bigtable/bttest): deal with non-ASCII characters in regex
  bigtable/bttest/inmem.go
  bigtable/bttest/inmem_test.go
  bigtable/integration_test.go
Labels: api: bigtable, cla: yes

#3827 fix(pubsublite): ackTracker should discard new acks after committer terminates
  pubsublite/internal/wire/acks.go
  pubsublite/internal/wire/acks_test.go
Labels: api: pubsublite, cla: yes

#3835 docs(pubsublite): clarifications for publish
  pubsublite/README.md
  pubsublite/pscompat/example_test.go
  pubsublite/pscompat/publisher.go
Labels: api: pubsublite, automerge, cla: yes

#3839 chore(internal/apidiff): enable apidiff for all release levels
  internal/apidiff/apidiff.go
Labels: cla: yes

#3840 chore(internal/apidiff): check for bang breaking change indicator
  internal/apidiff/apidiff.go
  internal/apidiff/apidiff_test.go
Labels: cla: yes

#3812 test(logging): add kokoro build script for environment tests
  internal/kokoro/environment.sh
Labels: api: logging, cla: yes, priority: p2, type: process

#3851 chore: ga clients
  internal/gapicgen/generator/config.go
Labels: cla: yes

#3850 feat(dialogflow/cx): start generating apiv3
  dialogflow/cx/apiv3/agents_client.go
  dialogflow/cx/apiv3/agents_client_example_test.go
  dialogflow/cx/apiv3/doc.go
  dialogflow/cx/apiv3/entity_types_client.go
  dialogflow/cx/apiv3/entity_types_client_example_test.go
  dialogflow/cx/apiv3/environments_client.go
  dialogflow/cx/apiv3/environments_client_example_test.go
  dialogflow/cx/apiv3/experiments_client.go
  dialogflow/cx/apiv3/experiments_client_example_test.go
  dialogflow/cx/apiv3/flows_client.go
  dialogflow/cx/apiv3/flows_client_example_test.go
  dialogflow/cx/apiv3/gapic_metadata.json
  dialogflow/cx/apiv3/intents_client.go
  dialogflow/cx/apiv3/intents_client_example_test.go
  dialogflow/cx/apiv3/pages_client.go
  dialogflow/cx/apiv3/pages_client_example_test.go
  dialogflow/cx/apiv3/security_settings_client.go
  dialogflow/cx/apiv3/security_settings_client_example_test.go
  dialogflow/cx/apiv3/session_entity_types_client.go
  dialogflow/cx/apiv3/session_entity_types_client_example_test.go
  dialogflow/cx/apiv3/sessions_client.go
  dialogflow/cx/apiv3/sessions_client_example_test.go
  dialogflow/cx/apiv3/test_cases_client.go
  dialogflow/cx/apiv3/test_cases_client_example_test.go
  dialogflow/cx/apiv3/transition_route_groups_client.go
  dialogflow/cx/apiv3/transition_route_groups_client_example_test.go
  dialogflow/cx/apiv3/versions_client.go
  dialogflow/cx/apiv3/versions_client_example_test.go
  dialogflow/cx/apiv3/webhooks_client.go
  dialogflow/cx/apiv3/webhooks_client_example_test.go
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: api: dialogflow, cla: yes

#3853 feat(documentai): start generating apiv1
  documentai/apiv1/doc.go
  documentai/apiv1/document_processor_client.go
  documentai/apiv1/document_processor_client_example_test.go
  documentai/apiv1/gapic_metadata.json
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: api: documentai, automerge, cla: yes

#3854 feat(resourcesettings): start generating apiv1
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  resourcesettings/apiv1/doc.go
  resourcesettings/apiv1/gapic_metadata.json
  resourcesettings/apiv1/resource_settings_client.go
  resourcesettings/apiv1/resource_settings_client_example_test.go
Labels: automerge, cla: yes

#3855 chore(logging): make environment test script executable
  internal/kokoro/environment.sh
Labels: api: logging, automerge, cla: yes, priority: p2

#3848 chore(internal/gapicgen): fix commit message processing
  internal/gapicgen/generator/generator.go
Labels: automerge, cla: yes

#3858 test(logging): change environment test script python version
  internal/kokoro/environment.sh
Labels: api: logging, cla: yes

#3843 fix(pubsublite): remove publish error translation
  pubsublite/internal/wire/publish_batcher_test.go
  pubsublite/pscompat/publisher.go
  pubsublite/pscompat/publisher_test.go
Labels: api: pubsublite, cla: yes

#3790 feat(pubsublite): adding ability to create subscriptions at head
  pubsublite/admin.go
  pubsublite/admin_test.go
Labels: api: pubsublite, cla: yes

#3846 fix(pubsublite): improve handling of backend unavailability
  pubsublite/internal/wire/errors.go
  pubsublite/internal/wire/rpc.go
  pubsublite/internal/wire/settings.go
  pubsublite/internal/wire/streams.go
  pubsublite/internal/wire/streams_test.go
  pubsublite/pscompat/example_test.go
  pubsublite/pscompat/publisher.go
  pubsublite/pscompat/settings.go
Labels: api: pubsublite, cla: yes

#3869 docs(pubsub): remove trailing experimental notices
  pubsub/subscription.go
Labels: api: pubsub, cla: yes

#3871 chore(internal/gapicgen): use API Service Config not gapic config
  internal/gapicgen/generator/config.go
  internal/gapicgen/generator/config_test.go
Labels: cla: yes

#3341 feat(spanner): Add support for RPC priority
  spanner/client.go
  spanner/client_test.go
  spanner/integration_test.go
  spanner/pdml.go
  spanner/transaction.go
Labels: api: spanner, cla: yes

#3803 docs(spanner): fix the result handling after BufferWrite
  spanner/doc.go
  spanner/examples_test.go
Labels: api: spanner, cla: yes
