Repository googleapis/google-cloud-go, pull requests merged in 2021-04, with the labels that each got.

#3878 fix(internal/godocfx): filter out non-Cloud
  internal/godocfx/godocfx_test.go
  internal/godocfx/main.go
  internal/godocfx/parse.go
Labels: cla: yes

#3882 docs: update a few URLs in example documentation
  examples_test.go
Labels: automerge: exact, cla: yes

#3877 feat(bigquery): export HivePartitioningOptions in load job configurations
  bigquery/external.go
  bigquery/load.go
  bigquery/load_test.go
Labels: api: bigquery, cla: yes

#3886 fix(pubsub): respect subscription message ordering field in scheduler
  pubsub/integration_test.go
  pubsub/pullstream_test.go
  pubsub/subscription.go
Labels: api: pubsub, cla: yes

#3233 feat(spanner): support request and transaction tags
  spanner/client.go
  spanner/client_test.go
  spanner/pdml.go
  spanner/pdml_test.go
  spanner/transaction.go
Labels: api: spanner, automerge, cla: yes

#3891 chore(all): fix username in blunderbuss
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#3895 test(bigquery): add integration test for Column ACLs
  bigquery/integration_test.go
Labels: api: bigquery, cla: yes

#3120 fix(logging): Entries has a 24H default filter
  logging/logadmin/logadmin.go
  logging/logadmin/logadmin_test.go
Labels: api: logging, automerge, cla: yes, priority: p2, type: feature request

#3902 test(bigquery): add testing for retry predicate
  bigquery/bigquery.go
  bigquery/bigquery_test.go
Labels: api: bigquery, automerge, cla: yes

#3907 chore: release bigquery 1.17.0
  bigquery/CHANGES.md
Labels: autorelease: pending, cla: yes

#3863 feat(logging): make toLogEntry function public
  logging/examples_test.go
  logging/logging.go
  logging/logging_test.go
  logging/logging_unexported_test.go
Labels: api: logging, cla: yes, priority: p2, type: feature request

#3917 refactor(internal/godocfx): move pkg loading to separate package
  internal/godocfx/parse.go
  internal/godocfx/pkgload/load.go
Labels: cla: yes

#3922 feat(internal/gensnippets): initial commit
  internal/gensnippets/go.mod
  internal/gensnippets/go.sum
  internal/gensnippets/main.go
Labels: cla: yes

#3924 feat(internal/gensnippets): add license header and region tags
  internal/gensnippets/main.go
Labels: automerge, cla: yes

#3909 feat(logging): cloud run and functions resource autodetection
  .gitignore
  logging/logging.go
Labels: api: logging, automerge, cla: yes, priority: p2

#3931 fix(internal/gensnippets): run goimports
  internal/gensnippets/main.go
Labels: automerge, cla: yes

#3933 chore(internal/gapicgen): use protoc 3.12.2
  internal/gapicgen/cmd/genbot/Dockerfile
Labels: automerge, cla: yes

#3929 chore(logging): trigger correct release semver
  logging/logging.go
Labels: api: logging, automerge, cla: yes, priority: p2

#3938 chore(all): un-gitignore file not in repo
  .gitignore
Labels: automerge, cla: yes, priority: p2, type: process

#3946 chore(.github): add hengfengli as spanner owner
  .github/CODEOWNERS
Labels: cla: yes

#3945 chore(.github): change default assignee to hengfengli for Spanner issues
  .github/blunderbuss.yml
Labels: cla: yes

#3913 test(spanner): fix flaky TestErrorOnPrepareSession
  spanner/session_test.go
Labels: api: spanner, cla: yes

#3915 test(spanner): fix flaky TestReadWriteTransaction_ContextTimeoutDuringDuringCommit
  spanner/client_test.go
Labels: api: spanner, cla: yes

#3949 feat(internal): auto-generate snippets
  internal/gapicgen/cmd/genbot/Dockerfile
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
  internal/generated/snippets/accessapproval/apiv1/Client/ApproveApprovalRequest/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/DeleteAccessApprovalSettings/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/DismissApprovalRequest/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/GetAccessApprovalSettings/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/GetApprovalRequest/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/ListApprovalRequests/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/NewClient/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/UpdateAccessApprovalSettings/main.go
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/gensnippets/cmd/gensnippets/main.go
  internal/gensnippets/gensnippets.go
Labels: cla: yes

#3951 refactor(internal/gapicgen): move cmdWrapper to new package
  internal/gapicgen/cmd/genbot/bot.go
  internal/gapicgen/cmd/genbot/generate.go
  internal/gapicgen/cmd/genbot/github.go
  internal/gapicgen/cmd/genbot/main.go
  internal/gapicgen/cmd/genbot/update.go
  internal/gapicgen/execv/command.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/generator/generator.go
  internal/gapicgen/generator/genproto.go
  internal/gapicgen/generator/git.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
Labels: cla: yes

#3953 chore(.github): force renovate to use 1.16
  .github/renovate.json
Labels: automerge, cla: yes

#3955 test: check mod version when no Go files in root
  internal/kokoro/build_samples.sh
Labels: cla: yes

#3954 refactor(internal): move gensnippets into gapicgen
  internal/gapicgen/cmd/gensnippets/main.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/gensnippets/gensnippets.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
  internal/gensnippets/go.mod
  internal/gensnippets/go.sum
Labels: automerge, cla: yes

#3957 fix(storage): retry io.ErrUnexpectedEOF
  storage/go110.go
  storage/go110_test.go
Labels: api: storage, cla: yes

#3962 feat(internal): generate region tags for snippets
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/gensnippets/gensnippets.go
  internal/generated/snippets/accessapproval/apiv1/Client/ApproveApprovalRequest/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/DeleteAccessApprovalSettings/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/DismissApprovalRequest/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/GetAccessApprovalSettings/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/GetApprovalRequest/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/ListApprovalRequests/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/NewClient/main.go
  internal/generated/snippets/accessapproval/apiv1/Client/UpdateAccessApprovalSettings/main.go
Labels: automerge, cla: yes

#3968 docs: fix link in contib
  CONTRIBUTING.md
Labels: cla: yes

#3971 chore(internal): ignore staticcheck in internal/generated/snippets
  internal/kokoro/vet.sh
Labels: cla: yes

#3972 chore(internal): ignore golint for internal/generated/snippets
  internal/kokoro/vet.sh
Labels: cla: yes

#3905 feat(spanner): enable request options for batch read
  spanner/batch.go
  spanner/client_test.go
  spanner/internal/testutil/inmem_spanner_server.go
Labels: api: spanner, cla: yes

#3974 chore(internal): add LibraryType to repo-metadata
  internal/gapicgen/generator/gapics.go
Labels: cla: yes

#3978 chore(storage): release 1.14.0
  storage/CHANGES.md
Labels: api: storage, cla: yes

#3982 chore(storage): release 1.15.0
  storage/CHANGES.md
Labels: api: storage, cla: yes

#3987 Revert "feat(spanner): enable request options for batch read"
  spanner/batch.go
  spanner/client_test.go
  spanner/internal/testutil/inmem_spanner_server.go
Labels: api: spanner, cla: yes

#3989 Revert "feat(spanner): support request and transaction tags"
  spanner/client.go
  spanner/client_test.go
  spanner/pdml.go
  spanner/pdml_test.go
  spanner/transaction.go
Labels: api: spanner, cla: yes

#3996 chore(spanner): release 1.18.0
  spanner/CHANGES.md
Labels: api: spanner, cla: yes

#3985 fix(pubsub): make config call permission error in Receive transparent
  pubsub/subscription.go
Labels: api: pubsub, cla: yes

#4003 fix(pubsub): fix failing message storage policy tests
  pubsub/integration_test.go
Labels: api: pubsub, cla: yes

#4002 chore(spanner): release 1.18.0
  spanner/CHANGES.md
Labels: api: spanner, cla: yes

#3950 feat(bigquery): support mutable clustering configuration
  bigquery/table.go
  bigquery/table_test.go
Labels: api: bigquery, cla: yes

#3960 docs: update CONTRIBUTING.md links
  CONTRIBUTING.md
Labels: automerge: exact, cla: yes, kokoro:force-run

#4015 chore(internal/gapicgen): add regen-only flag
  internal/gapicgen/cmd/genbot/local.go
  internal/gapicgen/cmd/genbot/main.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/generator/generator.go
Labels: automerge, cla: yes

#3899 feat(bigtable): Customer Managed Encryption (CMEK)
  CONTRIBUTING.md
  bigtable/admin.go
  bigtable/go.sum
  bigtable/integration_test.go
Labels: api: bigtable, cla: yes

#4026 test(firestore): add additional test verifying deleting a map value via update
  firestore/integration_test.go
Labels: cla: yes

#4029 build: switch release-please type to go-yoshi
  .github/workflows/release.yaml
Labels: cla: yes
