Repository googleapis/google-cloud-go, pull requests merged in 2021-09, with the labels that each got.

#4564 test(pubsublite): fix flaky TestAssigningSubscriberAddRemovePartitions
  pubsublite/internal/wire/subscriber_test.go
Labels: cla: yes, api: pubsublite

#4347 feat(firestore): Support DocumentRefs in OrderBy, Add Query.Serialize, Query.Deserialize for cross machine serialization
  firestore/collgroupref.go
  firestore/doc.go
  firestore/integration_test.go
  firestore/query.go
  firestore/query_test.go
Labels: cla: yes

#4714 fix(compute/metadata): fix retry logic to not panic on error
  compute/metadata/metadata.go
  compute/metadata/metadata_go113_test.go
  compute/metadata/retry.go
  compute/metadata/retry_test.go
Labels: cla: yes, api: compute, automerge

#4715 fix(storage): align retry idempotency (part 1)
  storage/acl.go
  storage/hmac.go
  storage/notifications.go
  storage/storage.go
Labels: api: storage, cla: yes

#4721 test(firestore): Expand partition queries test to help root out a flaky test
  firestore/integration_test.go
Labels: api: firestore, cla: yes

#4712 chore(all): auto-regenerate gapics
  aiplatform/apiv1/doc.go
  aiplatform/apiv1/gapic_metadata.json
  aiplatform/apiv1/vizier_client.go
  aiplatform/apiv1/vizier_client_example_test.go
  aiplatform/go.mod
  aiplatform/go.sum
  dialogflow/cx/apiv3beta1/agents_client.go
  dialogflow/cx/apiv3beta1/doc.go
  dialogflow/cx/apiv3beta1/test_cases_client.go
  dialogflow/go.mod
  dialogflow/go.sum
  go.mod
  go.sum
  internal/generated/snippets/aiplatform/apiv1/VizierClient/AddTrialMeasurement/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/CheckTrialEarlyStoppingState/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/CompleteTrial/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/CreateStudy/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/CreateTrial/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/DeleteStudy/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/DeleteTrial/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/GetStudy/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/GetTrial/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/ListOptimalTrials/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/ListStudies/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/ListTrials/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/LookupStudy/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/StopTrial/main.go
  internal/generated/snippets/aiplatform/apiv1/VizierClient/SuggestTrials/main.go
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/godocfx/go.sum
Labels: cla: yes, automerge

#4723 docs(spanner): add comment in doc on how to use SPANNER_EMULATOR_HOST
  spanner/doc.go
Labels: api: spanner, cla: yes

#4729 refactor(bigquery/storage/managedwriter): change AppendRows behavior
  bigquery/storage/managedwriter/appendresult.go
  bigquery/storage/managedwriter/appendresult_test.go
  bigquery/storage/managedwriter/integration_test.go
  bigquery/storage/managedwriter/managed_stream.go
Labels: api: bigquery, cla: yes

#4292 feat(pubsub): add publisher flow control support
  pubsub/flow_controller.go
  pubsub/flow_controller_test.go
  pubsub/integration_test.go
  pubsub/subscription.go
  pubsub/topic.go
  pubsub/topic_test.go
Labels: api: pubsub, cla: yes

#4731 chore: Update CODEOWNERS for @googleapis/cloud-storage-dpe
  .github/CODEOWNERS
Labels: cla: yes, automerge

#4607 feat(pubsub): add list configs for topic & sub
  pubsub/subscription.go
  pubsub/subscription_test.go
  pubsub/topic.go
  pubsub/topic_test.go
Labels: api: pubsub, cla: yes

#4725 chore(all): auto-regenerate gapics
  asset/apiv1/doc.go
  asset/go.mod
  asset/go.sum
  bigquery/go.mod
  bigquery/go.sum
  bigquery/reservation/apiv1/doc.go
  bigquery/reservation/apiv1/gapic_metadata.json
  bigquery/reservation/apiv1/reservation_client.go
  bigquery/reservation/apiv1/reservation_client_example_test.go
  bigquery/storage/apiv1beta2/big_query_read_client.go
  bigquery/storage/apiv1beta2/doc.go
  dialogflow/apiv2/agents_client.go
  dialogflow/apiv2/doc.go
  dialogflow/apiv2/documents_client.go
  dialogflow/apiv2/entity_types_client.go
  dialogflow/apiv2/intents_client.go
  dialogflow/go.mod
  dialogflow/go.sum
  internal/generated/snippets/bigquery/reservation/apiv1/Client/SearchAllAssignments/main.go
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/generated/snippets/osconfig/apiv1/OsConfigZonalClient/GetInventory/main.go
  internal/generated/snippets/osconfig/apiv1/OsConfigZonalClient/GetVulnerabilityReport/main.go
  internal/generated/snippets/osconfig/apiv1/OsConfigZonalClient/ListInventories/main.go
  internal/generated/snippets/osconfig/apiv1/OsConfigZonalClient/ListVulnerabilityReports/main.go
  osconfig/apiv1/doc.go
  osconfig/apiv1/gapic_metadata.json
  osconfig/apiv1/os_config_zonal_client.go
  osconfig/apiv1/os_config_zonal_client_example_test.go
  osconfig/go.mod
  osconfig/go.sum
Labels: cla: yes, automerge

#4739 chore(all): auto-regenerate gapics
  asset/go.sum
  bigquery/go.mod
  bigquery/go.sum
  channel/apiv1/cloud_channel_client.go
  channel/apiv1/cloud_channel_client_example_test.go
  channel/apiv1/doc.go
  channel/apiv1/gapic_metadata.json
  channel/go.mod
  channel/go.sum
  dialogflow/go.sum
  go.mod
  go.sum
  internal/generated/snippets/channel/apiv1/CloudChannelClient/ImportCustomer/main.go
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/godocfx/go.sum
  osconfig/go.sum
Labels: cla: yes, automerge

#4730 chore(spanner): modify benchwrapper's proto to use Singers/Albums
  spanner/go.sum
  spanner/internal/benchwrapper/main.go
  spanner/internal/benchwrapper/proto/spanner.pb.go
  spanner/internal/benchwrapper/proto/spanner.proto
  spanner/internal/benchwrapper/proto/spanner_grpc.pb.go
Labels: api: spanner, cla: yes

#4733 fix(pubsub): prevent draining error return for Receive
  pubsub/internal/scheduler/receive_scheduler.go
  pubsub/subscription.go
Labels: api: pubsub, cla: yes

#4743 feat(spanner/spansql): Support multiple joins in query
  spanner/spannertest/integration_test.go
  spanner/spansql/parser.go
  spanner/spansql/sql_test.go
Labels: api: spanner, cla: yes, automerge

#4753 chore(gapicgen): update microgen and promote compute to beta
  internal/gapicgen/cmd/genbot/Dockerfile
  internal/gapicgen/generator/config.go
Labels: cla: yes

#4294 feat(pubsublite): support reservations in AdminClient
  pubsublite/admin.go
  pubsublite/admin_test.go
  pubsublite/config.go
  pubsublite/config_test.go
  pubsublite/example_test.go
Labels: cla: yes, api: pubsublite

#4371 test(pubsublite): integration tests for reservations
  pubsublite/integration_test.go
Labels: cla: yes, api: pubsublite

#4756 fix(internal/gapicgen): add a temporary import
  compute/apiv1/doc.go
  go.mod
Labels: cla: yes, automerge

#4748 feat: expose the query source of a rowiterator via SourceJob()
  bigquery/integration_test.go
  bigquery/iterator.go
  bigquery/iterator_test.go
Labels: cla: yes, automerge

#4735 refactor(pubsublite): allow publish/subscribe for regional resources
  pubsublite/admin.go
  pubsublite/integration_test.go
  pubsublite/internal/wire/resources.go
  pubsublite/internal/wire/resources_test.go
  pubsublite/pscompat/integration_test.go
  pubsublite/pscompat/publisher.go
  pubsublite/pscompat/subscriber.go
Labels: cla: yes, api: pubsublite

#4746 chore: bulk gen
  accesscontextmanager/CHANGES.md
  accesscontextmanager/README.md
  accesscontextmanager/apiv1/access_context_manager_client.go
  accesscontextmanager/apiv1/access_context_manager_client_example_test.go
  accesscontextmanager/apiv1/doc.go
  accesscontextmanager/apiv1/gapic_metadata.json
  accesscontextmanager/go.mod
  accesscontextmanager/go.sum
  contactcenterinsights/CHANGES.md
  contactcenterinsights/README.md
  contactcenterinsights/apiv1/contact_center_insights_client.go
  contactcenterinsights/apiv1/contact_center_insights_client_example_test.go
  contactcenterinsights/apiv1/doc.go
  contactcenterinsights/apiv1/gapic_metadata.json
  contactcenterinsights/go.mod
  contactcenterinsights/go.sum
  internal/.repo-metadata-full.json
  internal/gapicgen/cmd/genbot/local.go
  internal/gapicgen/cmd/genbot/main.go
  internal/gapicgen/execv/gocmd/gocmd.go
  internal/gapicgen/generator/_CHANGES.md.txt
  internal/gapicgen/generator/_README.md.txt
  internal/gapicgen/generator/config.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/generator/generator.go
  monitoring/metricsscope/apiv1/doc.go
  monitoring/metricsscope/apiv1/gapic_metadata.json
  monitoring/metricsscope/apiv1/metrics_scopes_client.go
  monitoring/metricsscope/apiv1/metrics_scopes_client_example_test.go
  networkconnectivity/apiv1/doc.go
  networkconnectivity/apiv1/gapic_metadata.json
  networkconnectivity/apiv1/hub_client.go
  networkconnectivity/apiv1/hub_client_example_test.go
  networksecurity/CHANGES.md
  networksecurity/README.md
  networksecurity/apiv1beta1/doc.go
  networksecurity/apiv1beta1/gapic_metadata.json
  networksecurity/apiv1beta1/network_security_client.go
  networksecurity/apiv1beta1/network_security_client_example_test.go
  networksecurity/go.mod
  networksecurity/go.sum
  resourcemanager/apiv3/doc.go
  resourcemanager/apiv3/folders_client.go
  resourcemanager/apiv3/folders_client_example_test.go
  resourcemanager/apiv3/gapic_metadata.json
  resourcemanager/apiv3/organizations_client.go
  resourcemanager/apiv3/organizations_client_example_test.go
  resourcemanager/apiv3/projects_client.go
  resourcemanager/apiv3/projects_client_example_test.go
  resourcemanager/apiv3/tag_bindings_client.go
  resourcemanager/apiv3/tag_bindings_client_example_test.go
  resourcemanager/apiv3/tag_keys_client.go
  resourcemanager/apiv3/tag_keys_client_example_test.go
  resourcemanager/apiv3/tag_values_client.go
  resourcemanager/apiv3/tag_values_client_example_test.go
Labels: cla: yes

#4761 chore(all): auto-regenerate gapics
  go.mod
  go.sum
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/generated/snippets/recaptchaenterprise/apiv1/Client/GetMetrics/main.go
  internal/generated/snippets/recaptchaenterprise/apiv1/Client/MigrateKey/main.go
  internal/godocfx/go.sum
  recaptchaenterprise/apiv1/doc.go
  recaptchaenterprise/apiv1/gapic_metadata.json
  recaptchaenterprise/apiv1/recaptcha_enterprise_client.go
  recaptchaenterprise/apiv1/recaptcha_enterprise_client_example_test.go
  recaptchaenterprise/go.mod
  recaptchaenterprise/go.sum
Labels: cla: yes, automerge

#4768 test: skip some consistently failing tests
  firestore/integration_test.go
  storage/integration_test.go
Labels: cla: yes, automerge

#4771 docs(datastore): clarify documentation of omitempty
  datastore/doc.go
Labels: api: datastore, cla: yes, automerge

#4617 chore(storage): add gRPC-based Writer prototype
  storage/integration_test.go
  storage/reader.go
  storage/storage.go
  storage/storage_test.go
  storage/writer.go
Labels: api: storage, cla: yes

#4773 chore(storage): skip CancelWriteGRPC test
  storage/integration_test.go
Labels: api: storage, cla: yes, automerge

#4742 feat(spanner/spannertest): Support generated columns
  spanner/spannertest/README.md
  spanner/spannertest/db.go
  spanner/spannertest/db_eval.go
  spanner/spannertest/db_test.go
  spanner/spannertest/funcs.go
  spanner/spannertest/integration_test.go
Labels: api: spanner, cla: yes

#4769 test(compute): fix a flaky test
  compute/apiv1/smoke_test.go
Labels: cla: yes, api: compute, automerge

#4754 feat(bigquery): add session and connection support
  bigquery/integration_test.go
  bigquery/job.go
  bigquery/query.go
  bigquery/query_test.go
Labels: api: bigquery, cla: yes, automerge

#4788 feat: migrate managedwriter to v1 write from v1beta2
  bigquery/storage/managedwriter/adapt/protoconversion.go
  bigquery/storage/managedwriter/adapt/protoconversion_test.go
  bigquery/storage/managedwriter/adapt/schemaconversion.go
  bigquery/storage/managedwriter/adapt/schemaconversion_test.go
  bigquery/storage/managedwriter/appendresult.go
  bigquery/storage/managedwriter/client.go
  bigquery/storage/managedwriter/doc.go
  bigquery/storage/managedwriter/managed_stream.go
  bigquery/storage/managedwriter/managed_stream_test.go
Labels: cla: yes, automerge

#4786 test(spanner): fix tests for new error wrapping
  spanner/cmp_test.go
  spanner/go.mod
  spanner/go.sum
  spanner/session_test.go
Labels: api: spanner, cla: yes, automerge

#4302 docs(datastore): time.Time retrieved locale is UTC
  datastore/doc.go
  datastore/prop.go
Labels: api: datastore, cla: yes

#4799 chore(internal/gapicgen): enable generation of bigquery/migration/v2alpha
  internal/gapicgen/generator/config.go
Labels: cla: yes

#4764 docs(storage): replace misleading project ID
  storage/example_test.go
Labels: cla: yes, automerge

#4796 chore(all): auto-regenerate gapics
  bigquery/connection/apiv1beta1/doc.go
  bigquery/go.mod
  bigquery/go.sum
  bigquery/storage/apiv1/big_query_read_client.go
  bigquery/storage/apiv1/doc.go
  go.mod
  go.sum
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/godocfx/go.sum
Labels: cla: yes, automerge

#4797 feat(internal): provide wrapping for retried errors
  internal/retry.go
  internal/retry_test.go
Labels: cla: yes, automerge

#4807 chore(.github): don't run release-please on forks
  .github/workflows/release-submodule.yaml
  .github/workflows/release.yaml
Labels: cla: yes, automerge

#4810 chore: release accessapproval 1.0.0
  accessapproval/CHANGES.md
Labels: cla: yes, api: accessapproval

#4811 fix(accessapproval): testing formatting change
  accessapproval/CHANGES.md
Labels: cla: yes, api: accessapproval

#4812 chore: release asset 1.0.1
  asset/CHANGES.md
Labels: cla: yes, autorelease: pending

#4819 fix(accessapproval): testing formatting change
  accessapproval/CHANGES.md
Labels: cla: yes, api: accessapproval

#4821 chore: release aiplatform 1.0.0
  aiplatform/CHANGES.md
Labels: cla: yes

#4822 chore: release apigateway 1.0.0
  apigateway/CHANGES.md
Labels: cla: yes

#4823 chore: release apigeeconnect 1.0.0
  apigeeconnect/CHANGES.md
Labels: cla: yes

#4824 chore: release appengine 1.0.0
  appengine/CHANGES.md
Labels: cla: yes

#4825 chore: release artifactregistry 1.0.0
  artifactregistry/CHANGES.md
Labels: cla: yes

#4826 chore: release asset 1.0.0
  asset/CHANGES.md
Labels: cla: yes

#4827 chore: release automl 1.0.0
  automl/CHANGES.md
Labels: cla: yes

#4829 chore: release channel 1.0.0
  channel/CHANGES.md
Labels: cla: yes

#4830 chore: release cloudbuild 1.0.0
  cloudbuild/CHANGES.md
Labels: cla: yes

#4831 chore: release clouddms 1.0.0
  clouddms/CHANGES.md
Labels: cla: yes

#4832 chore: release cloudtasks 1.0.0
  cloudtasks/CHANGES.md
Labels: cla: yes

#4833 chore: release container 1.0.0
  container/CHANGES.md
Labels: cla: yes

#4834 chore: release datacatalog 1.0.0
  datacatalog/CHANGES.md
Labels: cla: yes

#4835 chore: release datafusion 1.0.0
  datafusion/CHANGES.md
Labels: cla: yes

#4885 chore: release workflows 1.0.0
  workflows/CHANGES.md
Labels: cla: yes

#4884 chore: release websecurityscanner 1.0.0
  websecurityscanner/CHANGES.md
Labels: cla: yes

#4883 chore: release webrisk 1.0.0
  webrisk/CHANGES.md
Labels: cla: yes

#4882 chore: release vpcaccess 1.0.0
  vpcaccess/CHANGES.md
Labels: cla: yes

#4881 chore: release vision 1.0.0
  vision/CHANGES.md
Labels: cla: yes

#4880 chore: release videointelligence 1.0.0
  videointelligence/CHANGES.md
Labels: cla: yes

#4879 chore: release video 1.0.0
  video/CHANGES.md
Labels: cla: yes

#4878 chore: release translate 1.0.0
  translate/CHANGES.md
Labels: cla: yes

#4877 chore: release trace 1.0.0
  trace/CHANGES.md
Labels: cla: yes

#4876 chore: release tpu 1.0.0
  tpu/CHANGES.md
Labels: cla: yes

#4875 chore: release texttospeech 1.0.0
  texttospeech/CHANGES.md
Labels: cla: yes

#4874 chore: release storagetransfer 1.0.0
  storagetransfer/CHANGES.md
Labels: cla: yes

#4873 chore: release speech 1.0.0
  speech/CHANGES.md
Labels: cla: yes

#4872 chore: release shell 1.0.0
  shell/CHANGES.md
Labels: cla: yes

#4871 chore: release serviceusage 1.0.0
  serviceusage/CHANGES.md
Labels: cla: yes

#4870 chore: release servicemanagement 1.0.0
  servicemanagement/CHANGES.md
Labels: cla: yes

#4869 chore: release servicedirectory 1.0.0
  servicedirectory/CHANGES.md
Labels: cla: yes

#4868 chore: release servicecontrol 1.0.0
  servicecontrol/CHANGES.md
Labels: cla: yes

#4867 chore: release securitycenter 1.0.0
  securitycenter/CHANGES.md
Labels: cla: yes

#4866 chore: release security 1.0.0
  security/CHANGES.md
Labels: cla: yes

#4865 chore: release secretmanager 1.0.0
  secretmanager/CHANGES.md
Labels: cla: yes

#4864 chore: release scheduler 1.0.0
  scheduler/CHANGES.md
Labels: cla: yes

#4863 chore: release retail 1.0.0
  retail/CHANGES.md
Labels: cla: yes

#4862 chore: release resourcesettings 1.0.0
  resourcesettings/CHANGES.md
Labels: cla: yes

#4861 chore: release resourcemanager 1.0.0
  resourcemanager/CHANGES.md
Labels: cla: yes

#4860 chore: release redis 1.0.0
  redis/CHANGES.md
Labels: cla: yes

#4859 chore: release recommender 1.0.0
  recommender/CHANGES.md
Labels: cla: yes

#4858 chore: release recaptchaenterprise 1.0.0
  recaptchaenterprise/CHANGES.md
Labels: cla: yes

#4857 chore: release policytroubleshooter 1.0.0
  policytroubleshooter/CHANGES.md
Labels: cla: yes

#4856 chore: release oslogin 1.0.0
  oslogin/CHANGES.md
Labels: cla: yes

#4855 chore: release osconfig 1.0.0
  osconfig/CHANGES.md
Labels: cla: yes

#4854 chore: release orgpolicy 1.0.0
  orgpolicy/CHANGES.md
Labels: cla: yes

#4853 chore: release networkmanagement 1.0.0
  networkmanagement/CHANGES.md
Labels: cla: yes

#4852 chore: release monitoring 1.0.0
  monitoring/CHANGES.md
Labels: cla: yes

#4851 chore: release metastore 1.0.0
  metastore/CHANGES.md
Labels: cla: yes

#4850 chore: release memcache 1.0.0
  memcache/CHANGES.md
Labels: cla: yes

#4849 chore: release managedidentities 1.0.0
  managedidentities/CHANGES.md
Labels: cla: yes

#4848 chore: release language 1.0.0
  language/CHANGES.md
Labels: cla: yes

#4847 chore: release kms 1.0.0
  kms/CHANGES.md
Labels: cla: yes

#4845 chore: release iap 1.0.0
  iap/CHANGES.md
Labels: cla: yes

#4844 chore: release gsuiteaddons 1.0.0
  gsuiteaddons/CHANGES.md
Labels: cla: yes

#4843 chore: release gaming 1.0.0
  gaming/CHANGES.md
Labels: cla: yes

#4842 chore: release functions 1.0.0
  functions/CHANGES.md
Labels: cla: yes

#4841 chore: release eventarc 1.0.0
  eventarc/CHANGES.md
Labels: cla: yes

#4840 chore: release essentialcontacts 1.0.0
  essentialcontacts/CHANGES.md
Labels: cla: yes

#4839 chore: release documentai 1.0.0
  documentai/CHANGES.md
Labels: cla: yes

#4838 chore: release dlp 1.0.0
  dlp/CHANGES.md
Labels: cla: yes

#4836 chore: release dataproc 1.0.0
  dataproc/CHANGES.md
Labels: cla: yes

#4837 chore: release dialogflow 1.0.0
  dialogflow/CHANGES.md
Labels: cla: yes

#4894 test(storage): skip "unspecified" PAP tests
  storage/integration_test.go
Labels: api: storage, cla: yes

#4893 chore(orchestration): start generating orchestration module
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
  internal/gapicgen/generator/gapics.go
  orchestration/CHANGES.md
  orchestration/README.md
  orchestration/airflow/service/apiv1/doc.go
  orchestration/airflow/service/apiv1/environments_client.go
  orchestration/airflow/service/apiv1/environments_client_example_test.go
  orchestration/airflow/service/apiv1/gapic_metadata.json
  orchestration/airflow/service/apiv1/image_versions_client.go
  orchestration/airflow/service/apiv1/image_versions_client_example_test.go
  orchestration/go.mod
  orchestration/go.sum
Labels: cla: yes

#4808 feat(spanner/spansql): fill in missing hash functions
  spanner/spansql/keywords.go
Labels: api: spanner, cla: yes, automerge

#4728 feat(civil): add IsEmpty function to time, date and datetime
  civil/civil.go
  civil/civil_test.go
Labels: cla: yes

#4899 feat(internal/godocfx): detect preview versions
  internal/godocfx/pkgload/load.go
  internal/godocfx/pkgload/load_test.go
Labels: cla: yes

#4624 docs: Update README.md
  README.md
Labels: cla: yes

#4900 test(bigtable): randomize instance name to avoid collision
  bigtable/integration_test.go
Labels: api: bigtable, cla: yes

#4805 feat(storage): add projectNumber field to bucketAttrs.
  storage/bucket.go
  storage/bucket_test.go
  storage/integration_test.go
Labels: api: storage, cla: yes

#4902 test(all): add Retry func to testutil from samples repository
  internal/testutil/retry.go
  internal/testutil/retry_test.go
Labels: api: bigtable, cla: yes

#4908 fix(firestore): prefer exact matches when reflecting fields
  firestore/document_test.go
  firestore/from_value.go
Labels: api: firestore, cla: yes

#4912 fix(README): update readme supported APIs to point to ref docs
  README.md
Labels: cla: yes

#4904 chore(all): auto-regenerate gapics
  aiplatform/apiv1/doc.go
  aiplatform/go.mod
  aiplatform/go.sum
  contactcenterinsights/apiv1/doc.go
  contactcenterinsights/go.mod
  contactcenterinsights/go.sum
  monitoring/go.mod
  monitoring/go.sum
  monitoring/metricsscope/apiv1/doc.go
Labels: cla: yes

#4918 chore(all): auto-regenerate gapics
  aiplatform/apiv1/doc.go
  aiplatform/go.mod
  aiplatform/go.sum
  bigquery/go.mod
  bigquery/go.sum
  bigquery/migration/apiv2alpha/doc.go
  dialogflow/cx/apiv3beta1/agents_client.go
  dialogflow/cx/apiv3beta1/deployments_client.go
  dialogflow/cx/apiv3beta1/deployments_client_example_test.go
  dialogflow/cx/apiv3beta1/doc.go
  dialogflow/cx/apiv3beta1/environments_client.go
  dialogflow/cx/apiv3beta1/environments_client_example_test.go
  dialogflow/cx/apiv3beta1/flows_client.go
  dialogflow/cx/apiv3beta1/gapic_metadata.json
  dialogflow/cx/apiv3beta1/test_cases_client.go
  dialogflow/cx/apiv3beta1/versions_client.go
  dialogflow/go.mod
  dialogflow/go.sum
  go.mod
  go.sum
  internal/generated/snippets/dialogflow/cx/apiv3beta1/DeploymentsClient/GetDeployment/main.go
  internal/generated/snippets/dialogflow/cx/apiv3beta1/DeploymentsClient/ListDeployments/main.go
  internal/generated/snippets/dialogflow/cx/apiv3beta1/EnvironmentsClient/DeployFlow/main.go
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/generated/snippets/orchestration/airflow/service/apiv1/EnvironmentsClient/CreateEnvironment/main.go
  internal/generated/snippets/orchestration/airflow/service/apiv1/EnvironmentsClient/DeleteEnvironment/main.go
  internal/generated/snippets/orchestration/airflow/service/apiv1/EnvironmentsClient/GetEnvironment/main.go
  internal/generated/snippets/orchestration/airflow/service/apiv1/EnvironmentsClient/ListEnvironments/main.go
  internal/generated/snippets/orchestration/airflow/service/apiv1/EnvironmentsClient/UpdateEnvironment/main.go
  internal/generated/snippets/orchestration/airflow/service/apiv1/ImageVersionsClient/ListImageVersions/main.go
  internal/godocfx/go.sum
  kms/apiv1/doc.go
  kms/go.mod
  kms/go.sum
Labels: cla: yes

#4930 chore: start generating filestore mod
  filestore/CHANGES.md
  filestore/README.md
  filestore/apiv1/cloud_filestore_manager_client.go
  filestore/apiv1/cloud_filestore_manager_client_example_test.go
  filestore/apiv1/doc.go
  filestore/apiv1/gapic_metadata.json
  filestore/go.mod
  filestore/go.sum
  internal/.repo-metadata-full.json
  internal/gapicgen/generator/config.go
Labels: cla: yes

#4763 test(pubsublite): simplify comparisons in integration tests
  pubsublite/integration_test.go
Labels: cla: yes, automerge, api: pubsublite
