Repository googleapis/google-cloud-go, pull requests merged in 2023-02, with the labels that each got.

#7332 feat(spanner): add support for Optimistic Concurrency Control
  spanner/client_test.go
  spanner/transaction.go
Labels: api: spanner, size: m

#7330 chore(all): auto-regenerate gapics
  container/apiv1/containerpb/cluster_service.pb.go
  container/go.mod
  container/go.sum
  go.mod
  go.sum
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/godocfx/go.mod
  internal/godocfx/go.sum
  vmwareengine/apiv1/vmwareenginepb/vmwareengine.pb.go
  vmwareengine/apiv1/vmwareenginepb/vmwareengine_resources.pb.go
  vmwareengine/go.mod
  vmwareengine/go.sum
Labels: size: xl

#7337 chore(all): auto-regenerate gapics
  dataplex/apiv1/data_scan_client.go
  dataplex/apiv1/dataplexpb/datascans.pb.go
  internal/generated/snippets/certificatemanager/apiv1/snippet_metadata.google.cloud.certificatemanager.v1.json
  internal/generated/snippets/dataplex/apiv1/snippet_metadata.google.cloud.dataplex.v1.json
  internal/generated/snippets/documentai/apiv1/snippet_metadata.google.cloud.documentai.v1.json
  internal/generated/snippets/documentai/apiv1beta3/snippet_metadata.google.cloud.documentai.v1beta3.json
  internal/generated/snippets/networkconnectivity/apiv1/snippet_metadata.google.cloud.networkconnectivity.v1.json
  internal/generated/snippets/networkconnectivity/apiv1alpha1/snippet_metadata.google.cloud.networkconnectivity.v1alpha1.json
  speech/apiv1/speechpb/cloud_speech_adaptation.pb.go
  speech/apiv1/speechpb/resource.pb.go
  speech/apiv1p1beta1/speechpb/cloud_speech_adaptation.pb.go
  speech/apiv1p1beta1/speechpb/resource.pb.go
Labels: automerge, size: m

#7327 chore: move cloud dir clients to owlbot
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
  internal/gapicgen/generator/gapics.go
Labels: size: l

#7341 chore: update supported versions of Go runtime
  README.md
Labels: size: xs

#7355 chore: temp disable some targets that don't build
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
Labels: size: m

#7356 chore: disable a few more owlbot configs
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
Labels: size: s

#7361 chore: disable oslogin owlbot gen
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
Labels: automerge, size: s

#7367 chore: stop eventarc pub because package name error
  .github/.OwlBot.yaml
Labels: size: xs

#7368 chore(third_party): remove unneeded 1.15 and 1.16 build constraints
  internal/godocfx/godocfx_test.go
  internal/godocfx/index.go
  internal/godocfx/index_test.go
  internal/godocfx/main.go
  internal/godocfx/parse.go
  internal/godocfx/timesaver.go
  third_party/pkgsite/print_type.go
Labels: size: s

#7370 refactor: cleanup old interface-based access in retry
  bigquery/bigquery.go
Labels: size: xs

#7371 chore: be more explicit with remove regex
  .github/.OwlBot.yaml
Labels: automerge, size: l

#7300 feat(internal/postprocessor): only regen snippets for changed modules
  internal/postprocessor/main.go
Labels: automerge, size: m

#7386 feat(maps/mapsplatformdatasets): start generating apiv1alpha
  internal/.repo-metadata-full.json
  internal/aliasfix/mappings.go
  internal/gapicgen/generator/config.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
  maps/mapsplatformdatasets/apiv1alpha/doc.go
  maps/mapsplatformdatasets/apiv1alpha/gapic_metadata.json
  maps/mapsplatformdatasets/apiv1alpha/maps_platform_datasets_v1_alpha_client.go
  maps/mapsplatformdatasets/apiv1alpha/maps_platform_datasets_v1_alpha_client_example_test.go
  maps/mapsplatformdatasets/apiv1alpha/mapsplatformdatasetspb/data_source.pb.go
  maps/mapsplatformdatasets/apiv1alpha/mapsplatformdatasetspb/dataset.pb.go
  maps/mapsplatformdatasets/apiv1alpha/mapsplatformdatasetspb/maps_platform_datasets.pb.go
  maps/mapsplatformdatasets/apiv1alpha/mapsplatformdatasetspb/maps_platform_datasets_alpha_service.pb.go
  maps/mapsplatformdatasets/apiv1alpha/version.go
Labels: size: xl

#7392 fix(longrunning): properly parse errors with apierror
  longrunning/longrunning.go
  longrunning/longrunning_test.go
Labels: size: s

#7385 feat(orgpolicy): start generating apiv1
  .github/.OwlBot.yaml
Labels: api: orgpolicy, size: xs

#7395 test(storage): skip notification tests
  storage/client_test.go
Labels: api: storage, automerge, size: xs

#7396 chore(internal/gapicgen): reduce openssh build reqs
  internal/gapicgen/cmd/genbot/Dockerfile
Labels: size: xs

#7397 chore(internal/gapicgen): skip generating some snipets
  internal/gapicgen/generator/gapics.go
Labels: automerge

#7374 refactor: migrate settings and options
  bigquery/storage/managedwriter/client.go
  bigquery/storage/managedwriter/managed_stream.go
  bigquery/storage/managedwriter/managed_stream_test.go
  bigquery/storage/managedwriter/options.go
  bigquery/storage/managedwriter/options_test.go
Labels: size: m

#7388 test(storage): enable some GRPC test stragglers
  storage/integration_test.go
Labels: api: storage, size: m

#7288 feat(internal/postprocessor): detect and initialize new modules
  internal/postprocessor/README.md
  internal/postprocessor/_README.md.txt
  internal/postprocessor/_internal_version.go.txt
  internal/postprocessor/_version.go.txt
  internal/postprocessor/main.go
  internal/postprocessor/modconfig.go
Labels: automerge, size: l

#7403 test(storage): add retry on GRPC empty ACL on UBLA enabled bucket
  storage/integration_test.go
Labels: api: storage, size: m

#7408 chore: revert broken google.golang.org/api to working rev
  storage/go.mod
  storage/go.sum
Labels: automerge, size: xs

#7404 fix(internal/postprocessor): add scopes without OwlBot api-name feature
  .github/.OwlBot.yaml
  internal/postprocessor/main.go
  internal/postprocessor/main_test.go
Labels: automerge, size: l

#7376 fix(datastore): adds nil check to AggregationQuery
  datastore/query.go
  datastore/query_test.go
Labels: api: datastore, size: s

#7320 fix(logging): correctly populate SourceLocation when logging via (*Logger).StandardLogger
  logging/logging.go
  logging/logging_test.go
Labels: api: logging, size: m

#7415 chore(storage): update google.golang.org/api
  storage/go.mod
  storage/go.sum
Labels: automerge

#7417 test(storage): unskip notification tests
  storage/client_test.go
Labels: api: storage, automerge, size: xs

#7421 fix(spanner/spannertest): begin new transaction for streaming queries in R/W transactions
  spanner/spannertest/inmem.go
Labels: api: spanner, kokoro:force-run, size: s

#7271 fix(storage): specify credentials with STORAGE_EMULATOR_HOST
  storage/storage.go
  storage/storage_test.go
Labels: api: storage, size: s

#7427 feat(discoveryengine): start generating apiv1beta
  discoveryengine/CHANGES.md
  discoveryengine/README.md
  discoveryengine/apiv1beta/discoveryenginepb/common.pb.go
  discoveryengine/apiv1beta/discoveryenginepb/document.pb.go
  discoveryengine/apiv1beta/discoveryenginepb/document_service.pb.go
  discoveryengine/apiv1beta/discoveryenginepb/import_config.pb.go
  discoveryengine/apiv1beta/discoveryenginepb/recommendation_service.pb.go
  discoveryengine/apiv1beta/discoveryenginepb/user_event.pb.go
  discoveryengine/apiv1beta/discoveryenginepb/user_event_service.pb.go
  discoveryengine/apiv1beta/doc.go
  discoveryengine/apiv1beta/document_client.go
  discoveryengine/apiv1beta/document_client_example_test.go
  discoveryengine/apiv1beta/gapic_metadata.json
  discoveryengine/apiv1beta/recommendation_client.go
  discoveryengine/apiv1beta/recommendation_client_example_test.go
  discoveryengine/apiv1beta/user_event_client.go
  discoveryengine/apiv1beta/user_event_client_example_test.go
  discoveryengine/apiv1beta/version.go
  discoveryengine/go.mod
  discoveryengine/go.sum
  discoveryengine/internal/version.go
  internal/.repo-metadata-full.json
  internal/aliasfix/mappings.go
  internal/gapicgen/generator/config.go
Labels: size: xl, api: discoveryengine

#7158 feat(storage): json downloads
  storage/doc.go
  storage/go.mod
  storage/go.sum
  storage/grpc_client.go
  storage/http_client.go
  storage/integration_test.go
  storage/option.go
  storage/option_test.go
  storage/reader.go
  storage/reader_test.go
  storage/retry_conformance_test.go
  storage/retry_test.go
  storage/storage.go
Labels: api: storage, stale: extraold, size: xl

#7420 chore(storage): adjust GRPC reader remain - off by one
  storage/grpc_client.go
Labels: api: storage, size: s

#7431 feat(discoveryengine): add library to release-please
  .release-please-manifest-submodules.json
  release-please-config-yoshi-submodules.json
Labels: automerge, size: xs, api: discoveryengine

#7434 fix(artifactregistry): remove unintentionally published proto
  artifactregistry/apiv1/artifactregistrypb/kfp_artifact.pb.go
Labels: breaking change, breaking change allowed

#7436 chore: generate more proto stubs
  apigeeregistry/apiv1/apigeeregistrypb/provisioning_service.pb.go
  apigeeregistry/apiv1/apigeeregistrypb/registry_models.pb.go
  apigeeregistry/apiv1/apigeeregistrypb/registry_service.pb.go
  apikeys/apiv2/apikeyspb/apikeys.pb.go
  apikeys/apiv2/apikeyspb/resources.pb.go
  dialogflow/apiv2beta1/dialogflowpb/agent.pb.go
  dialogflow/apiv2beta1/dialogflowpb/answer_record.pb.go
  dialogflow/apiv2beta1/dialogflowpb/audio_config.pb.go
  dialogflow/apiv2beta1/dialogflowpb/context.pb.go
  dialogflow/apiv2beta1/dialogflowpb/conversation.pb.go
  dialogflow/apiv2beta1/dialogflowpb/conversation_event.pb.go
  dialogflow/apiv2beta1/dialogflowpb/conversation_profile.pb.go
  dialogflow/apiv2beta1/dialogflowpb/document.pb.go
  dialogflow/apiv2beta1/dialogflowpb/entity_type.pb.go
  dialogflow/apiv2beta1/dialogflowpb/environment.pb.go
  dialogflow/apiv2beta1/dialogflowpb/fulfillment.pb.go
  dialogflow/apiv2beta1/dialogflowpb/gcs.pb.go
  dialogflow/apiv2beta1/dialogflowpb/human_agent_assistant_event.pb.go
  dialogflow/apiv2beta1/dialogflowpb/intent.pb.go
  dialogflow/apiv2beta1/dialogflowpb/knowledge_base.pb.go
  dialogflow/apiv2beta1/dialogflowpb/participant.pb.go
  dialogflow/apiv2beta1/dialogflowpb/session.pb.go
  dialogflow/apiv2beta1/dialogflowpb/session_entity_type.pb.go
  dialogflow/apiv2beta1/dialogflowpb/validation_result.pb.go
  dialogflow/apiv2beta1/dialogflowpb/version.pb.go
  dialogflow/apiv2beta1/dialogflowpb/webhook.pb.go
  iam/apiv2/iampb/deny.pb.go
  iam/apiv2/iampb/policy.pb.go
  internal/.repo-metadata-full.json
  internal/aliasfix/mappings.go
Labels: automerge, size: xl

#7441 chore: update post processor rev
  .github/.OwlBot.lock.yaml
Labels: size: xs

#7418 feat(bigquery): add support for session in load jobs
  bigquery/integration_test.go
  bigquery/load.go
  bigquery/load_test.go
  bigquery/query.go
Labels: api: bigquery, automerge, size: m

#7455 chore(internal/gapicgen): fix dockerfile build
  internal/gapicgen/cmd/genbot/Dockerfile
Labels: automerge, size: xs

#7429 feat(spanner/spansql): add support for missing DDL syntax for ALTER CHANGE STREAM
  spanner/spansql/parser.go
  spanner/spansql/parser_test.go
  spanner/spansql/sql.go
  spanner/spansql/sql_test.go
  spanner/spansql/types.go
Labels: api: spanner, size: l

#7476 test(storage): skip bucket update tests for gRPC
  storage/integration_test.go
Labels: api: storage, automerge, size: s

#7430 chore(storage): add range reads to benchmarks
  storage/internal/benchmarks/README.md
  storage/internal/benchmarks/download_benchmark.go
  storage/internal/benchmarks/main.go
  storage/internal/benchmarks/w1r3.go
Labels: api: storage, size: m

#7467 fix(bigquery): avoid double-channel-close during context cancellation
  bigquery/storage/managedwriter/managed_stream.go
  bigquery/storage/managedwriter/managed_stream_test.go
Labels: api: bigquery, automerge, size: m

#7478 chore: onboard oslogin/common
  .github/.OwlBot.yaml
Labels: automerge, size: xs

#7486 refactor(bigquery/storage/managedwriter): make send optimizers safer
  bigquery/storage/managedwriter/send_optimizer.go
Labels: size: m

#7477 chore(internal/postprocessor): some refactoring and fixes
  .github/.OwlBot.lock.yaml
  internal/postprocessor/main.go
  internal/postprocessor/main_test.go
  internal/postprocessor/testdata/add-commit-delimiters.input
  internal/postprocessor/testdata/add-commit-delimiters.output
  internal/postprocessor/testdata/nested-client-scope.input
  internal/postprocessor/testdata/nested-client-scope.output
  internal/postprocessor/testdata/nested-commits.input
  internal/postprocessor/testdata/nested-commits.output
  internal/postprocessor/testdata/separate-multiple-commits.input
  internal/postprocessor/testdata/separate-multiple-commits.output
  internal/postprocessor/testdata/separate-multiple-commits2.input
  internal/postprocessor/testdata/separate-multiple-commits2.output
Labels: automerge, size: l

#7494 test(storage): skip 2 more tests for gRPC
  storage/integration_test.go
Labels: api: storage, automerge, size: xs

#7490 refactor(bigquery/storage/managedwriter): add custom client options
  bigquery/storage/managedwriter/options.go
  bigquery/storage/managedwriter/options_test.go
Labels: api: bigquery, size: m

#7362 fix(pubsub): allow updating topic schema fields individually
  pubsub/pstest/fake.go
  pubsub/topic.go
  pubsub/topic_test.go
Labels: api: pubsub, automerge, size: m

#6804 feat(bigquery/storage/managedwriter): mark managedwriter as GA
  bigquery/storage/managedwriter/doc.go
Labels: api: bigquery, stale: extraold, size: xs
