Repository googleapis/google-cloud-go, pull requests merged in 2023-10, with the labels that each got.

#8625 feat(auth): add grpctransport package
  auth/go.mod
  auth/go.sum
  auth/grpctransport/dial_socketopt.go
  auth/grpctransport/dial_socketopt_test.go
  auth/grpctransport/directpath.go
  auth/grpctransport/grpctransport.go
  auth/grpctransport/grpctransport_test.go
  auth/grpctransport/pool.go
  auth/grpctransport/pool_test.go
  auth/grpctransport/testdata/README.md
  auth/grpctransport/testdata/echo.pb.go
  auth/grpctransport/testdata/echo.proto
  auth/grpctransport/testdata/echo_grpc.pb.go
  auth/impersonate/integration_test.go
  auth/internal/transport/cba.go
  auth/internal/transport/cba_test.go
  auth/oauth2adapt/go.sum
Labels: size: xl

#8636 chore(alloydb/connectors): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: automerge, size: xs, api: alloydb

#8580 feat(auth): add idtoken package
  auth/idtoken/cache.go
  auth/idtoken/cache_test.go
  auth/idtoken/compute.go
  auth/idtoken/compute_test.go
  auth/idtoken/examples_test.go
  auth/idtoken/file.go
  auth/idtoken/idtoken.go
  auth/idtoken/idtoken_test.go
  auth/idtoken/integration_test.go
  auth/idtoken/validate.go
  auth/idtoken/validate_test.go
  auth/impersonate/integration_test.go
Labels: size: xl

#8640 feat(bigquery): add media options to LoadConfig
  bigquery/bigquery.go
  bigquery/integration_test.go
  bigquery/load.go
Labels: api: bigquery, size: s

#8643 fix(internal/postprocessor): add ability to override release level
  internal/postprocessor/config.go
  internal/postprocessor/config.yaml
  internal/postprocessor/manifest.go
Labels: size: s

#8645 chore: bump postprocessor version
  .github/.OwlBot.lock.yaml
Labels: automerge, size: xs

#8646 fix(internal/postprocessor): add missing assignment
  internal/postprocessor/config.go
  internal/postprocessor/config_test.go
Labels: automerge, size: s

#8647 chore: bump postprocessor version
  .github/.OwlBot.lock.yaml
Labels: size: xs

#8648 feat(alloydb): start generating connectors apiv1
  alloydb/CHANGES.md
Labels: automerge, size: xs, api: alloydb

#8630 test(bigtable): Increase timeout for delete and restore table
  bigtable/integration_test.go
Labels: api: bigtable, size: xs

#8605 feat(pubsub/pstest): update max topic retention duration to 31 days
  pubsub/pstest/fake.go
  pubsub/topic.go
Labels: api: pubsub, size: s

#8654 feat(auth): add Credentials.UniverseDomain()
  auth/detect/detect.go
  auth/detect/detect_test.go
  auth/detect/filetypes.go
  auth/internal/internaldetect/filetype.go
  auth/internal/testdata/sa_universe_domain.json
  auth/internal/testdata/user_universe_domain.json
Labels: size: m

#8672 chore(shopping/merchant/inventories): add config to generate apiv1beta
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#8674 chore(shopping/merchant/inventories): fix config to generate apiv1beta
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#8676 chore(shopping/merchant/inventories): fix config.yaml to generate apiv1beta
  internal/postprocessor/config.yaml
Labels: size: xs

#8677 chore(internal/postprocessor): update Dockerfile to Go 1.21
  internal/postprocessor/Dockerfile
Labels: size: xs

#8679 chore(github): update Dockerfile SHA in .OwlBot.lock.yaml
  .github/.OwlBot.lock.yaml
Labels: size: xs

#8690 chore(internal/postprocessor): add config for shopping/type
  .github/.OwlBot.yaml
  go.work.sum
  internal/postprocessor/config.yaml
Labels: size: s

#8666 fix(bigquery): handle storage read api Recv call errors
  bigquery/storage_iterator.go
  bigquery/storage_iterator_test.go
Labels: api: bigquery, automerge, size: m

#8695 chore(ci): update Go version to 1.21
  .github/workflows/apidiff.yml
  .github/workflows/new_client.yml
  .github/workflows/vet.yml
  go.work.sum
Labels: automerge, size: s

#8712 test(spanner): fix data race issue in inmemory spanner test runs
  spanner/internal/testutil/inmem_spanner_server.go
Labels: api: spanner, size: s

#8716 chore(maps/fleetengine): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#8717 chore(maps/fleetengine/delivery): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#8719 chore(securesourcemanager): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#8718 chore(auth): add a bunch of missing validation logic
  auth/auth.go
  auth/auth_test.go
  auth/detect/detect.go
  auth/detect/detect_test.go
  auth/detect/filetypes.go
  auth/detect/internal/externalaccount/sts_exchange.go
  auth/detect/internal/impersonate/impersonate.go
  auth/detect/internal/impersonate/impersonate_test.go
  auth/idtoken/idtoken.go
  auth/impersonate/idtoken.go
  auth/impersonate/impersonate.go
  auth/internal/internaldetect/parse_test.go
  auth/internal/testdata/clientcreds_installed.json
  auth/threelegged.go
  auth/threelegged_test.go
Labels: size: l

#8733 chore(github): remove unused OwlBot configuration
  .github/.OwlBot.yaml
Labels: size: xs

#8698 chore(storage): add invocation ID to gRPC calls
  storage/grpc_client.go
  storage/hmac.go
  storage/http_client.go
  storage/invoke.go
  storage/invoke_test.go
  storage/reader.go
Labels: api: storage, automerge, size: l

#8670 feat(storage): support MatchGlob for gRPC
  storage/grpc_client.go
  storage/integration_test.go
Labels: api: storage, automerge, size: xs

#8658 test(bigtable): Run conformance tests for bigtable
  .github/workflows/conformance.yaml
  bigtable/conformance_test.sh
Labels: api: bigtable, size: m

#8730 fix(profiler): migrate to protobuf-go v2
  profiler/go.mod
  profiler/profiler.go
  profiler/profiler_test.go
Labels: api: cloudprofiler, automerge, size: s

#8657 fix(bigtable): return cluster error for Update when populated
  bigtable/admin.go
Labels: api: bigtable, automerge, size: xs

#8735 chore: add support for running module dir tests in continuous
  internal/kokoro/continuous.sh
Labels: automerge, size: xs

#8722 chore(internal/actions/cmd): add nested commit output to updateall
  internal/actions/cmd/updateall/README.md
  internal/actions/cmd/updateall/main.go
Labels: automerge, size: m

#8697 feat(auth): port external account changes
  auth/detect/detect_test.go
  auth/detect/doc.go
  auth/detect/filetypes.go
  auth/detect/internal/externalaccount/aws_provider.go
  auth/detect/internal/externalaccount/aws_provider_test.go
  auth/detect/internal/externalaccount/executable_provider.go
  auth/detect/internal/externalaccount/executable_provider_test.go
  auth/detect/internal/externalaccount/externalaccount.go
  auth/detect/internal/externalaccount/externalaccount_test.go
  auth/detect/internal/externalaccount/file_provider.go
  auth/detect/internal/externalaccount/file_provider_test.go
  auth/detect/internal/externalaccount/impersonate_test.go
  auth/detect/internal/externalaccount/info.go
  auth/detect/internal/externalaccount/info_test.go
  auth/detect/internal/externalaccount/url_provider.go
  auth/detect/internal/externalaccount/url_provider_test.go
  auth/detect/internal/externalaccountuser/externalaccountuser.go
  auth/detect/internal/externalaccountuser/externalaccountuser_test.go
  auth/detect/internal/stsexchange/sts_exchange.go
  auth/detect/internal/stsexchange/sts_exchange_test.go
  auth/internal/internaldetect/filetype.go
  auth/internal/internaldetect/internaldetect.go
  auth/internal/internaldetect/parse.go
  auth/internal/internaldetect/parse_test.go
  auth/internal/testdata/exaccount_user.json
Labels: size: l

#8293 feat(firestore): SUM and AVG aggregations
  firestore/integration_test.go
  firestore/query.go
  firestore/query_test.go
Labels: api: firestore, stale: extraold, size: l

#8747 feat(auth/oauth2adapt): fixup deps for release
  .release-please-manifest-submodules.json
  auth/oauth2adapt/go.mod
  auth/oauth2adapt/go.sum
  go.work.sum
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
Labels: automerge, size: l

#8750 chore(internal/actions): fix updateall
  CHANGES.md
  internal/actions/cmd/updateall/main.go
Labels: size: xs

#8506 feat(bigquery): expose Apache Arrow data through ArrowIterator
  bigquery/arrow.go
  bigquery/iterator.go
  bigquery/storage_bench_test.go
  bigquery/storage_integration_test.go
  bigquery/storage_iterator.go
  bigquery/storage_iterator_test.go
Labels: api: bigquery, automerge, stale: old, size: l

#8757 chore(internal/godocfx): update godocfx golden
  internal/godocfx/testdata/golden/index.yml
Labels: automerge, size: m

#8760 chore(internal/kokoro): try to fix VCS verification
  internal/kokoro/publish_docs.sh
Labels: automerge, size: xs

#8761 chore(internal/kokoro): set -buildvcs=false when installing godocfx
  internal/kokoro/publish_docs.sh
Labels: automerge, size: xs

#8653 feat(bigquery): introduce query preview features
  bigquery/bigquery.go
  bigquery/go.mod
  bigquery/go.sum
  bigquery/integration_test.go
  bigquery/iterator.go
  bigquery/query.go
  go.work.sum
Labels: api: bigquery, automerge, size: m

#8762 chore(internal/kokoro): fix doc upload
  internal/kokoro/publish_docs.sh
Labels: automerge, size: s

#8763 chore(internal/kokoro): upload docs to subdirectory
  internal/kokoro/publish_docs.sh
Labels: automerge, size: s

#8759 chore(internal/godocfx): test a specific golden package version
  internal/godocfx/go.mod
  internal/godocfx/godocfx_test.go
  internal/godocfx/main.go
  internal/godocfx/testdata/golden/cloud.google.com/go/storage@v1.33.0/index.yml
  internal/godocfx/testdata/golden/cloud.google.com/go/storage@v1.33.0/pkg-readme.md
  internal/godocfx/testdata/golden/cloud.google.com/go/storage@v1.33.0/toc.yml
Labels: automerge, size: m

#8686 feat(bigquery/storage/managedwriter): support default value controls
  bigquery/storage/managedwriter/appendresult.go
  bigquery/storage/managedwriter/appendresult_test.go
  bigquery/storage/managedwriter/client.go
  bigquery/storage/managedwriter/connection.go
  bigquery/storage/managedwriter/integration_test.go
  bigquery/storage/managedwriter/managed_stream.go
  bigquery/storage/managedwriter/managed_stream_test.go
  bigquery/storage/managedwriter/options.go
  bigquery/storage/managedwriter/options_test.go
  bigquery/storage/managedwriter/send_optimizer.go
  bigquery/storage/managedwriter/send_optimizer_test.go
  bigquery/storage/managedwriter/testdata/schemas.go
  bigquery/storage/managedwriter/testdata/testing.pb.go
  bigquery/storage/managedwriter/testdata/testing.proto
Labels: api: bigquery, automerge, size: l

#8766 chore(cloudquotas): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#8770 chore(cloudquotas): Revert "add config to generate apiv1 (#8766)"
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#8751 test(bigtable): Add retries while getting app profile
  bigtable/integration_test.go
Labels: api: bigtable, size: s

#8652 feat(spanner): BatchWrite
  spanner/client.go
  spanner/client_test.go
  spanner/integration_test.go
  spanner/internal/testutil/inmem_spanner_server.go
  spanner/internal/testutil/inmem_spanner_server_test.go
  spanner/mutation.go
  spanner/mutation_test.go
Labels: api: spanner, size: l

#8923 fix(spanner): Expose Mutations field in MutationGroup
  spanner/integration_test.go
  spanner/mutation.go
Labels: api: spanner, size: xs

#8872 fix(storage): drop stream reference after closing it for gRPC writes
  storage/grpc_client.go
Labels: api: storage, size: xs

#8713 feat(spanner): Auto-generated executor framework proto changes
  spanner/test/cloudexecutor/proto/README.md
  spanner/test/cloudexecutor/proto/cloud_executor.pb.go
  spanner/test/cloudexecutor/proto/cloud_executor.proto
Labels: api: spanner, size: xl

#8177 feat(spanner): long running transaction clean up - disabled
  spanner/client.go
  spanner/client_test.go
  spanner/pdml.go
  spanner/session.go
  spanner/session_test.go
  spanner/transaction.go
Labels: api: spanner, stale: extraold, size: l

#8939 chore(profiler): upgrade go version used in kokoro integration test
  profiler/kokoro/integration_test.sh
Labels: api: cloudprofiler, size: xs

#8721 feat(storage): support autoclass v2.1
  storage/bucket.go
  storage/bucket_test.go
  storage/integration_test.go
Labels: api: storage, automerge, size: m

#8753 fix(pubsub): set x-goog-request-params for streaming pull request
  pubsub/pullstream.go
Labels: api: pubsub, size: xs

#8947 chore(redis/cluster): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: api: redis, automerge, size: xs

#8765 test(pubsub): add retry guard to ordering key test
  pubsub/integration_test.go
Labels: api: pubsub, size: m

#8949 test(bigquery/storage/managedwriter): refactor large insert tests
  bigquery/storage/managedwriter/integration_test.go
Labels: api: bigquery, size: s
