Repository googleapis/google-cloud-go, pull requests merged in 2023-05, with the labels that each got.

#7844 chore(storage): fix range read validation check [benchmarking]
  storage/internal/benchmarks/main.go
Labels: api: storage, size: xs

#7856 chore(internal/postprocessor): add support for root dir OwlBot dest
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  internal/postprocessor/config.go
  internal/postprocessor/config.yaml
  internal/postprocessor/main.go
Labels: size: s

#7838 fix(bigquery/storage/managedwriter): schema evolution improvements
  bigquery/storage/managedwriter/connection.go
Labels: api: bigquery, automerge, size: s

#7799 chore(storage): round up Chunksize to nearest multiple of 256kib [GRPC]
  storage/grpc_client.go
  storage/integration_test.go
  storage/writer.go
Labels: api: storage, size: m

#7848 docs(bigquery/storage/managedwriter): improve tuning guidance
  bigquery/storage/managedwriter/doc.go
Labels: api: bigquery, automerge, size: s

#7773 chore(storage): continue on failures & ensure all runs are printed [benchmarking]
  storage/internal/benchmarks/README.md
  storage/internal/benchmarks/download_benchmark.go
  storage/internal/benchmarks/main.go
  storage/internal/benchmarks/utils.go
  storage/internal/benchmarks/w1r3.go
Labels: api: storage, size: l

#7860 chore(orgpolicy): remove broken version file
  orgpolicy/apiv1/version.go
Labels: automerge, api: orgpolicy, size: s

#7861 feat(confidentialcomputing): start generating apiv1
  confidentialcomputing/CHANGES.md
Labels: api: confidentialcomputing, size: xs

#7862 feat(storageinsights): start generating apiv1
  storageinsights/CHANGES.md
Labels: size: xs

#7580 fix(pubsub/pstest): start `DeliveryAttempt` at 1
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
Labels: api: pubsub, stale: old, size: s

#7650 fix(pubsub/pstest): Clear Subscription when calling `ClearMessages`.
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
Labels: api: pubsub, stale: old, size: s

#7872 chore(storage): fix progress call in gRPC Writer
  storage/grpc_client.go
  storage/integration_test.go
Labels: api: storage, size: s

#7875 chore(support): add config to generate apiv2
  .github/.OwlBot.yaml
  .release-please-manifest-submodules.json
  internal/postprocessor/config.yaml
  release-please-config-yoshi-submodules.json
Labels: size: s

#7874 docs(pubsub): clarify NumGoroutines configures number of streams
  pubsub/doc.go
  pubsub/subscription.go
Labels: api: pubsub, size: s

#7879 feat(support): start generating apiv2
  support/CHANGES.md
Labels: size: xs

#7881 docs(storage): WithXMLReads should mention XML instead of JSON API
  storage/option.go
Labels: api: storage, automerge: exact, size: xs

#7883 chore(internal/postprocessor): migrate all clients to OwlBot snippets
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xl

#7884 chore(internal/actions): refactor changefinder
  internal/actions/cmd/changefinder/README.md
  internal/actions/cmd/changefinder/main.go
Labels: automerge, size: m

#7889 chore(changefinder): add -base flag
  internal/actions/cmd/changefinder/README.md
  internal/actions/cmd/changefinder/main.go
Labels: automerge, size: xs

#7904 chore(internal/postprocessor): add modEditReplaceInSnippets for new modules
  internal/postprocessor/execv/gocmd/gocmd.go
  internal/postprocessor/main.go
Labels: size: s

#7909 chore(maps/places): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#7913 chore(maps/places): Revert "chore(maps/places): add config to generate apiv1 (#7909)"
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#7912 feat(spanner): make leader aware routing default enabled for supported RPC requests
  spanner/client.go
Labels: api: spanner, size: xs

#7918 chore(maps/places): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#7919 feat(maps/places): start generating apiv1
  maps/CHANGES.md
Labels: size: xs

#7920 chore(internal/gensnippets): remove unused module internal/gensnippets
  go.work
  internal/.repo-metadata-full.json
  internal/gensnippets/gensnippets.go
  internal/gensnippets/go.mod
  internal/gensnippets/go.sum
  internal/gensnippets/metadata/metadata.pb.go
  internal/gensnippets/metadata/metadata.proto
  internal/gensnippets/model.go
Labels: size: xl

#7929 chore(internal/godocfx): update testdata/golden/index.yml
  internal/godocfx/testdata/golden/index.yml
Labels: size: xs

#7935 chore: workspace owned by all
  .github/CODEOWNERS
Labels: size: xs

#7934 testing(bigquery/storage/managedwriter): test complex json schemas
  bigquery/storage/managedwriter/integration_test.go
  go.work.sum
Labels: api: bigquery, automerge, size: m

#7946 chore: remove storage samples
  .github/.OwlBot.yaml
  internal/generated/snippets/storage/internal/apiv2/Client/CancelResumableWrite/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/ComposeObject/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/CreateBucket/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/CreateHmacKey/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/CreateNotificationConfig/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/DeleteBucket/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/DeleteHmacKey/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/DeleteNotificationConfig/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/DeleteObject/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/GetBucket/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/GetHmacKey/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/GetIamPolicy/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/GetNotificationConfig/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/GetObject/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/GetServiceAccount/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/ListBuckets/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/ListHmacKeys/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/ListNotificationConfigs/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/ListObjects/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/LockBucketRetentionPolicy/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/QueryWriteStatus/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/RewriteObject/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/SetIamPolicy/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/StartResumableWrite/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/TestIamPermissions/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/UpdateBucket/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/UpdateHmacKey/main.go
  internal/generated/snippets/storage/internal/apiv2/Client/UpdateObject/main.go
  internal/generated/snippets/storage/internal/apiv2/snippet_metadata.google.storage.v2.json
Labels: automerge, samples, size: xl

#7949 chore: moves files to prep for automation
  internal/README.md
  internal/postprocessor/Dockerfile
  internal/postprocessor/README.md
  internal/postprocessor/cloudbuild.yaml
Labels: size: s

#7951 chore(bigtable): update the test proxy in accordance with the updated…
  bigtable/internal/testproxy/proxy.go
  bigtable/internal/testproxy/proxy_test.go
Labels: api: bigtable, automerge, size: s

#7952 chore: test new automation
  internal/postprocessor/cloudbuild.yaml
Labels: automerge, size: s

#7947 chore: fix manifest docs url
  .github/.OwlBot.lock.yaml
  internal/postprocessor/execv/gocmd/gocmd.go
Labels: size: s

#7954 chore(internal/postprocessor): update README
  internal/postprocessor/README.md
Labels: size: s

#7901 chore(internal/actions): add updateall command
  internal/actions/cmd/changefinder/main.go
  internal/actions/cmd/updateall/README.md
  internal/actions/cmd/updateall/main.go
  internal/actions/logg/logg.go
Labels: automerge, size: l

#7959 fix(spanner): fix TestRetryInfoTransactionOutcomeUnknownError flaky behaviour
  spanner/retry_test.go
Labels: api: spanner, kokoro:force-run, size: xs

#7940 feat(pubsub): expose common errors for easier handling
  pubsub/integration_test.go
  pubsub/topic.go
  pubsub/topic_test.go
Labels: api: pubsub, size: s

#7955 chore: move recaptcha to in-place versioning
  .github/.OwlBot.yaml
  .release-please-manifest-submodules.json
  go.work
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/postprocessor/config.yaml
  recaptchaenterprise/CHANGES.md
  recaptchaenterprise/apiv1/doc.go
  recaptchaenterprise/apiv1/gapic_metadata.json
  recaptchaenterprise/apiv1/recaptcha_enterprise_client.go
  recaptchaenterprise/apiv1/recaptcha_enterprise_client_example_test.go
  recaptchaenterprise/apiv1/recaptchaenterprisepb/recaptchaenterprise.pb.go
  recaptchaenterprise/apiv1/version.go
  recaptchaenterprise/apiv1beta1/doc.go
  recaptchaenterprise/apiv1beta1/gapic_metadata.json
  recaptchaenterprise/apiv1beta1/recaptcha_enterprise_service_v1_beta1_client.go
  recaptchaenterprise/apiv1beta1/recaptcha_enterprise_service_v1_beta1_client_example_test.go
  recaptchaenterprise/apiv1beta1/recaptchaenterprisepb/recaptchaenterprise.pb.go
  recaptchaenterprise/apiv1beta1/version.go
  recaptchaenterprise/go.mod
  recaptchaenterprise/go.sum
  recaptchaenterprise/internal/version.go
  recaptchaenterprise/v2/CHANGES.md
  recaptchaenterprise/v2/README.md
  recaptchaenterprise/v2/apiv1/doc.go
  recaptchaenterprise/v2/apiv1/recaptcha_enterprise_client.go
  recaptchaenterprise/v2/apiv1/recaptcha_enterprise_client_example_test.go
  recaptchaenterprise/v2/apiv1/version.go
  recaptchaenterprise/v2/apiv1beta1/doc.go
  recaptchaenterprise/v2/apiv1beta1/recaptcha_enterprise_service_v1_beta1_client.go
  recaptchaenterprise/v2/apiv1beta1/recaptcha_enterprise_service_v1_beta1_client_example_test.go
  recaptchaenterprise/v2/apiv1beta1/recaptchaenterprisepb/recaptchaenterprise.pb.go
  recaptchaenterprise/v2/apiv1beta1/version.go
  recaptchaenterprise/v2/go.mod
  recaptchaenterprise/v2/go.sum
  recaptchaenterprise/v2/internal/version.go
  release-please-config-yoshi-submodules.json
Labels: size: xl

#7963 chore(internal/postprocessor): auto-update release-please files
  internal/postprocessor/main.go
  internal/postprocessor/main_test.go
  internal/postprocessor/releaseplease.go
  internal/postprocessor/testdata/.release-please-manifest-submodules.json
  internal/postprocessor/testdata/.release-please-manifest-submodules.want
  internal/postprocessor/testdata/release-please-config-yoshi-submodules.want
Labels: automerge, size: m

#7899 feat(spanner): enable client to server compression
  spanner/client.go
  spanner/client_test.go
  spanner/integration_test.go
  spanner/pdml_test.go
Labels: api: spanner, size: m

#7969 chore(internal/postprocessor): add missing rel-path for recent v2 in-place conversions
  internal/postprocessor/config.yaml
Labels: size: xs

#7974 chore: fixup imports after version bump
  go.work.sum
  internal/gapicgen/git/github.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/postprocessor/go.mod
  internal/postprocessor/go.sum
  internal/postprocessor/main.go
Labels: size: m

#7975 test: fix tidy check to match all mod files
  .github/workflows/vet.sh
Labels: size: xs

#7981 chore(ci): ignore snippet go.mod in vet check
  .github/workflows/vet.sh
Labels: size: xs

#7980 fix(pubsub): allow clearing of topic schema
  pubsub/pstest/fake.go
  pubsub/topic.go
  pubsub/topic_test.go
Labels: api: pubsub, size: s

#7982 chore: fix genbot
  internal/gapicgen/cmd/genbot/Dockerfile
  internal/gapicgen/cmd/genbot/local.go
  internal/gapicgen/cmd/genbot/main.go
  internal/gapicgen/generator/generator.go
  internal/gapicgen/generator/genproto.go
Labels: size: m

#7986 chore(internal/gapicgen): let it end gracefully
  internal/gapicgen/cmd/genbot/generate.go
  internal/gapicgen/cmd/genbot/local.go
  internal/gapicgen/cmd/genbot/main.go
  internal/gapicgen/generator/generator.go
  internal/gapicgen/generator/genproto.go
Labels: automerge, size: s

#7987 chore(rapidmigrationassessment): add config to generate apiv1
  .github/.OwlBot.yaml
  .release-please-manifest-submodules.json
  internal/postprocessor/config.yaml
  release-please-config-yoshi-submodules.json
Labels: size: s

#7988 chore(discoveryengine): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs, api: discoveryengine

#7991 chore(ci): apidiff module mode with changefinder
  .github/workflows/apidiff.yml
Labels: automerge, size: s

#7965 feat(spanner): allow configuring batch timeout property in session client
  spanner/client.go
  spanner/client_test.go
  spanner/sessionclient.go
Labels: api: spanner, size: s

#7788 chore(main): Added kokoro release job
  .github/release-trigger.yml
  internal/kokoro/release.sh
  internal/kokoro/requirements.in
  internal/kokoro/requirements.txt
Labels: stale: old, size: l

#8005 chore: fix new module bug
  internal/postprocessor/main.go
Labels: size: xs

#8006 chore: bump post-processor rev
  .github/.OwlBot.lock.yaml
Labels: automerge, size: xs

#8012 chore: update missed dep bumps
  go.work
  go.work.sum
  rapidmigrationassessment/go.mod
  rapidmigrationassessment/go.sum
  storageinsights/go.mod
  storageinsights/go.sum
  support/go.mod
  support/go.sum
Labels: automerge

#8013 chore(internal/postprocessor): ensure new modules are added to workspace
  internal/postprocessor/execv/gocmd/gocmd.go
  internal/postprocessor/main.go
Labels: automerge, size: s

#8014 chore(internal/actions): have changefinder respect v2 mods
  internal/actions/cmd/changefinder/main.go
Labels: automerge, size: s

#8018 chore: io/ioutil deprecated
  httpreplay/cmd/httpr/httpr.go
  httpreplay/cmd/httpr/integration_test.go
  httpreplay/httpreplay_test.go
  httpreplay/internal/proxy/converter.go
  httpreplay/internal/proxy/converter_test.go
  httpreplay/internal/proxy/log.go
  httpreplay/internal/proxy/log_test.go
  httpreplay/internal/proxy/record.go
  httpreplay/internal/proxy/replay.go
  internal/pretty/diff.go
  internal/testutil/context.go
Labels: automerge: exact, size: m

#8019 chore: fix some sums
  rapidmigrationassessment/go.sum
  storageinsights/go.sum
  support/go.sum
Labels: automerge, size: s

#8020 test: retry create remote udf function
  bigquery/routine_integration_test.go
Labels: size: s
