Repository googleapis/google-cloud-go, pull requests merged in 2023-07, with the labels that each got.

#8202 fix(storage): update gRPC retry codes
  storage/invoke.go
  storage/invoke_test.go
Labels: api: storage, automerge, size: s

#8196 fix(internal/retry): Simplify gRPC status code mapping of retry error
  internal/retry.go
  internal/retry_test.go
Labels: automerge: exact, size: s

#8199 fix(pubsub/pstest): update maxMessageRetentionDuration to be 31 days
  pubsub/pstest/fake.go
Labels: api: pubsub, size: xs

#8212 chore(ai/generativelanguage): add config to generate apiv1beta2
  .github/.OwlBot.yaml
  .release-please-manifest-submodules.json
  internal/postprocessor/config.yaml
  release-please-config-yoshi-submodules.json
Labels: size: s

#8221 fix(logadmin): use consistent filter in paging example
  logging/logadmin/example_paging_test.go
Labels: automerge, size: s

#8226 test(bigquery): skip storage billing model tests
  bigquery/dataset_integration_test.go
Labels: api: bigquery, automerge, size: xs

#8222 fix(datastore): Return error from RunAggregationQuery
  datastore/client.go
  datastore/integration_test.go
Labels: api: datastore, size: m

#8229 feat(ai/generativelanguage): start generating apiv1beta2
  ai/CHANGES.md
Labels: size: xs

#8225 chore(storage): add GCSFuse client config [benchmarking]
  storage/internal/benchmarks/client_pool.go
  storage/internal/benchmarks/main.go
Labels: api: storage, size: m

#8191 chore(storage): add configurable per op timeout, print timeout [benchmarking]
  storage/internal/benchmarks/README.md
  storage/internal/benchmarks/directory_benchmark.go
  storage/internal/benchmarks/download_benchmark.go
  storage/internal/benchmarks/main.go
  storage/internal/benchmarks/upload_benchmark.go
  storage/internal/benchmarks/w1r3.go
Labels: api: storage, size: s

#8234 test(bigquery): delete stale datasets
  bigquery/integration_test.go
Labels: api: bigquery, automerge, size: s

#7025 chore(datastore): Add trace span for RunAggregationQuery.
  datastore/query.go
Labels: api: datastore, stale: extraold, size: xs

#8198 feat(bigtable/bttest): support reverse scans
  bigtable/bttest/inmem.go
  bigtable/bttest/inmem_test.go
  bigtable/go.mod
  bigtable/go.sum
Labels: api: bigtable, size: m

#8250 fix: kokoro presubmit builds
  internal/kokoro/continuous.sh
  internal/kokoro/presubmit.sh
Labels: size: xs

#8260 fix(httpreplay): ignore GCS header by default
  httpreplay/cmd/httpr/integration_test.go
  httpreplay/httpreplay_test.go
  httpreplay/internal/proxy/converter.go
Labels: automerge, size: s

#8267 test: skip failing tests
  bigtable/integration_test.go
  go.work.sum
  pubsub/integration_test.go
Labels: size: xs

#8263 chore(.github): add storage as httpreplay owner
  .github/CODEOWNERS
Labels: size: xs

#8269 chore(storage): add endpoint option to CLI [benchmarking]
  storage/internal/benchmarks/benchmark_result.go
  storage/internal/benchmarks/client_pool.go
  storage/internal/benchmarks/main.go
Labels: api: storage, size: s

#6869 test(pubsub): add retry guards to publish/receive test
  pubsub/integration_test.go
Labels: api: pubsub, stale: extraold, size: m

#8274 fix: add more docs to base package
  doc.go
Labels: automerge, size: m

#8285 feat(beyondcorp): promote to GA
  beyondcorp/CHANGES.md
Labels: automerge, size: xs

#8283 feat(advisorynotifications): promote to GA
  advisorynotifications/CHANGES.md
Labels: automerge, size: xs, api: advisorynotifications

#8262 test(storage): improve object cleanup
  storage/integration_test.go
Labels: api: storage, automerge, size: m

#7145 test(pubsub): update retry deadlines for exactly once tests
  pubsub/subscription_test.go
Labels: api: pubsub, stale: extraold, size: xs

#8287 chore: re-onboard cloudbuild apiv1 /w OwlBot
  .github/.OwlBot.yaml
Labels: automerge, size: xs

#8248 test(pubsub): add retry guard to cancel receive test
  pubsub/integration_test.go
Labels: api: pubsub, size: s

#8289 docs(ai): fix README.md title
  ai/README.md
Labels: automerge, size: xs

#8245 feat(spanner/spansql): add support for IF NOT EXISTS and IF EXISTS clause
  spanner/spansql/parser.go
  spanner/spansql/parser_test.go
  spanner/spansql/sql.go
  spanner/spansql/sql_test.go
  spanner/spansql/types.go
Labels: api: spanner, size: m

#8246 feat(spanner/spansql): add complete set of math functions
  spanner/spansql/keywords.go
Labels: api: spanner, size: s

#8290 feat(storageinsights): promote to GA
  storageinsights/CHANGES.md
Labels: size: xs

#8298 chore: skip compute folder in genproto
  internal/gapicgen/generator/genproto.go
Labels: automerge, size: xs

#8297 chore(storage): update grpc defaultConnPoolSize
  storage/grpc_client.go
Labels: api: storage, automerge, size: xs

#8300 chore(netapp): add config to generate apiv1beta1
  .github/.OwlBot.yaml
  .release-please-manifest-submodules.json
  internal/postprocessor/config.yaml
  release-please-config-yoshi-submodules.json
Labels: automerge, size: s

#8301 feat(confidentialcomputing): promote to GA
  confidentialcomputing/CHANGES.md
Labels: automerge, api: confidentialcomputing, size: xs

#8303 feat(gkemulticloud): promote to GA
  gkemulticloud/CHANGES.md
Labels: automerge, size: xs

#8304 feat(rapidmigrationassessment): promote to GA
  rapidmigrationassessment/CHANGES.md
Labels: automerge, size: xs

#8306 feat(vmwareengine): promote to GA
  vmwareengine/CHANGES.md
Labels: automerge, api: vmwareengine, size: xs

#8305 feat(support): promote to GA
  support/CHANGES.md
Labels: automerge, size: xs

#8302 feat(discoveryengine): promote to GA
  discoveryengine/CHANGES.md
Labels: automerge, size: xs, api: discoveryengine

#8275 fix(bigquery/storage/managedwriter): context refactoring
  bigquery/storage/managedwriter/client.go
  bigquery/storage/managedwriter/client_test.go
  bigquery/storage/managedwriter/connection.go
  bigquery/storage/managedwriter/connection_test.go
  bigquery/storage/managedwriter/integration_test.go
  bigquery/storage/managedwriter/managed_stream.go
  bigquery/storage/managedwriter/managed_stream_test.go
  bigquery/storage/managedwriter/routers_test.go
Labels: api: bigquery, size: l

#8310 chore(netapp): Revert "add config to generate apiv1beta1 (#8300)"
  .github/.OwlBot.yaml
  .release-please-manifest-submodules.json
  internal/postprocessor/config.yaml
  release-please-config-yoshi-submodules.json
Labels: size: s

#8296 feat(spanner/spansql): add support for foreign key actions
  spanner/spansql/parser.go
  spanner/spansql/parser_test.go
  spanner/spansql/sql.go
  spanner/spansql/sql_test.go
  spanner/spansql/types.go
Labels: api: spanner, size: m

#8292 feat(pubsub): support payload wrapping for push subs
  .github/workflows/vet.sh
  pubsub/pstest/fake.go
  pubsub/pstest/fake_test.go
  pubsub/subscription.go
  pubsub/subscription_test.go
Labels: api: pubsub, size: m

#8318 chore(commerce/consumer/procurement): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs

#8319 chore(ci): add profiler blunderbuss config
  .github/blunderbuss.yml
Labels: automerge, size: xs

#8322 feat(commerce): start generating apiv1
  commerce/CHANGES.md
Labels: size: xs

#8314 refactor(bigquery/storage/managedwriter): refactor error metrics
  bigquery/storage/managedwriter/connection.go
Labels: api: bigquery, automerge, size: s

#8324 feat(bigquery/storage/managedwriter): refine connection metrics
  bigquery/storage/managedwriter/connection.go
  bigquery/storage/managedwriter/instrumentation.go
  bigquery/storage/managedwriter/integration_test.go
Labels: api: bigquery, size: s

#7789 test(spanner): support Foreign Key On Delete Cascade
  spanner/integration_test.go
Labels: kokoro:force-run, stale: extraold, size: m

#8276 feat(datastore): Multi DB support
  CONTRIBUTING.md
  datastore/client.go
  datastore/datastore.go
  datastore/datastore_test.go
  datastore/integration_test.go
  datastore/key.go
  datastore/query.go
  datastore/transaction.go
  internal/kokoro/continuous.sh
Labels: api: datastore, size: m

#8313 test(storage): add retry to ACL tests that rely on eventual consistency
  storage/integration_test.go
Labels: api: storage, automerge, size: s

#8335 chore(policysimulator): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: automerge, size: xs

#8340 feat(policysimulator): start generating apiv1
  policysimulator/CHANGES.md
Labels: size: xs

#8338 chore(apidiff): ignore added files
  .github/workflows/apidiff.yml
  internal/actions/cmd/changefinder/main.go
Labels: automerge, size: s

#8343 feat(bigtable): Support last_scanned_row_key in emulator
  bigtable/bttest/inmem.go
  bigtable/bttest/inmem_test.go
  bigtable/bttest/validation_test.go
  bigtable/go.mod
  bigtable/go.sum
  bigtable/internal/option/option.go
Labels: api: bigtable, size: m

#8345 feat(bigtable): Support last_scanned_row in the bigtable client
  bigtable/bigtable.go
  bigtable/retry_test.go
Labels: api: bigtable, automerge, size: s

#8346 chore(netapp): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: automerge, size: xs

#8347 chore(alloydb/connectors): add config to generate apiv1alpha
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: xs, api: alloydb

#8349 chore(internal/postprocessor): skip generation of version.go for non-client packages
  internal/postprocessor/main.go
Labels: size: xs

#8350 chore(owlbot): update postprocessor sha
  .github/.OwlBot.lock.yaml
Labels: size: xs

#8353 feat(netapp): start generating apiv1
  netapp/CHANGES.md
Labels: size: xs

#8355 fix(datastore): Using env var instead of project ID
  CONTRIBUTING.md
Labels: api: datastore, size: xs

#8359 chore(internal/kokoro): skip tests for empty commits
  internal/kokoro/continuous.sh
  internal/kokoro/presubmit.sh
Labels: size: s

#8294 feat(storage): add support for custom headers
  storage/doc.go
  storage/go.mod
  storage/go.sum
  storage/headers_test.go
  storage/http_client.go
  storage/mock_test.go
Labels: api: storage, size: m
