Repository googleapis/google-cloud-go, pull requests merged in 2023-04, with the labels that each got.

#7589 feat(datastore): EntityFilter for AND/OR queries
  datastore/datastore_test.go
  datastore/integration_test.go
  datastore/query.go
  datastore/query_test.go
Labels: api: datastore, size: l

#7667 chore(all): auto-regenerate gapics
  aiplatform/go.mod
  aiplatform/go.sum
  analytics/go.mod
  analytics/go.sum
  asset/apiv1/asset_client.go
  asset/apiv1/assetpb/asset_service.pb.go
  asset/apiv1/assetpb/assets.pb.go
  asset/apiv1p5beta1/assetpb/assets.pb.go
  asset/go.mod
  asset/go.sum
  containeranalysis/go.mod
  containeranalysis/go.sum
  eventarc/go.mod
  eventarc/go.sum
  eventarc/publishing/apiv1/publishingpb/publisher.pb.go
  go.mod
  go.sum
  internal/gapicgen/generator/config.go
  internal/generated/snippets/eventarc/publishing/apiv1/snippet_metadata.google.cloud.eventarc.publishing.v1.json
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/generated/snippets/recaptchaenterprise/v2/apiv1beta1/snippet_metadata.google.cloud.recaptchaenterprise.v1beta1.json
  internal/godocfx/go.mod
  internal/godocfx/go.sum
  recaptchaenterprise/v2/apiv1beta1/doc.go
  recaptchaenterprise/v2/apiv1beta1/recaptchaenterprisepb/recaptchaenterprise.pb.go
  recaptchaenterprise/v2/go.mod
  recaptchaenterprise/v2/go.sum
  serviceusage/apiv1/serviceusagepb/resources.pb.go
  serviceusage/apiv1/serviceusagepb/serviceusage.pb.go
  serviceusage/go.mod
  serviceusage/go.sum
Labels: size: xl

#7681 chore(all): auto-regenerate gapics
  appengine/go.mod
  appengine/go.sum
  go.mod
  go.sum
  iap/go.mod
  iap/go.sum
  internal/generated/snippets/bigquery/analyticshub/apiv1/snippet_metadata.google.cloud.bigquery.analyticshub.v1.json
  internal/generated/snippets/go.mod
  internal/generated/snippets/go.sum
  internal/godocfx/go.mod
  internal/godocfx/go.sum
Labels: size: m

#7656 test(storage): separate out public object test and enable gRPC
  storage/integration_test.go
Labels: api: storage, size: m

#7622 chore(storage): benchmarking: allow range parameter for object size
  storage/internal/benchmarks/README.md
  storage/internal/benchmarks/main.go
Labels: api: storage, size: s

#7682 chore: decouple post processor from gapicgen
  internal/postprocessor/.gitignore
  internal/postprocessor/command.go
  internal/postprocessor/config.go
  internal/postprocessor/config.yaml
  internal/postprocessor/execv/gocmd/gocmd.go
  internal/postprocessor/go.mod
  internal/postprocessor/go.sum
  internal/postprocessor/main.go
  internal/postprocessor/main_test.go
  internal/postprocessor/manifest.go
  internal/postprocessor/modconfig.go
  internal/postprocessor/snippets.go
Labels: automerge, size: xl

#7690 chore: bump post processor revision
  .github/.OwlBot.lock.yaml
Labels: automerge, size: xs

#7691 chore: cleanup mod files
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
  internal/gensnippets/cmd/gensnippets/main.go
  internal/gensnippets/go.mod
  internal/gensnippets/go.sum
  internal/godocfx/go.mod
  internal/godocfx/go.sum
Labels: automerge, size: xl

#7652 chore(storage): handle bucket labels for gRPC
  storage/bucket.go
  storage/grpc_client.go
  storage/integration_test.go
Labels: api: storage, size: m

#7697 test(internal/postprocessor): load config for tests
  internal/postprocessor/command.go
  internal/postprocessor/config.go
  internal/postprocessor/go.mod
  internal/postprocessor/go.sum
  internal/postprocessor/main.go
  internal/postprocessor/main_test.go
Labels: automerge, size: l

#7670 test(pubsub): add retry guard to topic retention test
  pubsub/integration_test.go
Labels: api: pubsub, size: m

#7696 chore: upgrade deps and drop replace
  internal/gapicgen/cmd/genbot/local.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/git/git.go
  internal/gapicgen/git/github.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
Labels: automerge, size: m

#7693 fix(bigquery): respect context during query execution
  bigquery/bigquery.go
  bigquery/iam.go
  bigquery/inserter.go
  bigquery/integration_test.go
  bigquery/iterator.go
Labels: api: bigquery, automerge, size: s

#7702 chore: reenable maps gen
  .github/.OwlBot.yaml
Labels: automerge, size: xs

#7705 chore: onboard compute to owlbot
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/generator/genproto.go
  internal/postprocessor/config.yaml
Labels: automerge, size: s

#7688 chore(storage): handle object metadata (grpc)
  storage/grpc_client.go
  storage/integration_test.go
  storage/storage.go
Labels: api: storage, size: s

#7703 chore: cleanup gapicgen a bit
  internal/gapicgen/cmd/genbot/local.go
  internal/gapicgen/cmd/genbot/main.go
  internal/gapicgen/generator/config.go
  internal/gapicgen/generator/config_test.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/generator/generator.go
  internal/gapicgen/generator/genproto.go
Labels: automerge, size: xl

#7673 feat(bigquery/storage/managedwriter): expose connection multiplexing as experimental
  bigquery/storage/managedwriter/doc.go
  bigquery/storage/managedwriter/integration_test.go
  bigquery/storage/managedwriter/options.go
  bigquery/storage/managedwriter/options_test.go
Labels: api: bigquery, automerge, size: m

#7706 feat(bigquery): expose dataset MaxTimeTravelHours
  bigquery/dataset.go
  bigquery/dataset_integration_test.go
  bigquery/dataset_test.go
Labels: api: bigquery, size: s

#7707 refactor(bigquery): amend name for MaxTimeTravel on datasets
  bigquery/dataset.go
  bigquery/dataset_integration_test.go
  bigquery/dataset_test.go
Labels: api: bigquery, automerge, size: s

#7523 chore(internal/postprocessor): add MoveSnippets to main.go
  .github/.OwlBot.lock.yaml
  internal/postprocessor/main.go
Labels: size: s

#7712 fix: deadlock with inline begin transaction when first statement response is never returned
  spanner/client_test.go
  spanner/transaction.go
Labels: size: s

#7709 chore: reenable asset on owlbot
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
  internal/postprocessor/config.yaml
Labels: size: s

#7708 chore(internal): update postprocessor README instructions
  internal/README.md
  internal/postprocessor/README.md
Labels: automerge, size: m

#7713 chore(workstations): add config to generate apiv1
  internal/gapicgen/generator/config.go
  internal/postprocessor/config.yaml
Labels: automerge, size: s, api: workstations

#7715 chore(workstations): update OwlBot to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: size: s, api: workstations

#7716 chore: reenable eventarc/publishing v1
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
  internal/postprocessor/config.yaml
Labels: automerge, size: s

#7717 chore: migrate alloydb to owlbot
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
  internal/postprocessor/config.yaml
Labels: automerge, size: s

#7720 chore: bulk move more apis to owlbot
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
  internal/postprocessor/config.yaml
Labels: automerge, size: m

#7722 chore(ci): fix owlbot config syntax
  .github/.OwlBot.yaml
Labels: size: xs

#7723 chore(internal/postprocessor): fix version file package
  .github/.OwlBot.lock.yaml
  internal/postprocessor/main.go
Labels: size: s

#7730 chore(internal/gapicgen): remove more dead code
  internal/gapicgen/README.md
  internal/gapicgen/cmd/genbot/README.md
  internal/gapicgen/cmd/genbot/alias.go
  internal/gapicgen/cmd/genbot/generate.go
  internal/gapicgen/cmd/genbot/local.go
  internal/gapicgen/cmd/genbot/main.go
  internal/gapicgen/execv/gocmd/gocmd.go
  internal/gapicgen/generator/_README.md.txt
  internal/gapicgen/generator/_internal_version.go.txt
  internal/gapicgen/generator/_version.go.txt
  internal/gapicgen/generator/config_test.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/git/git.go
  internal/gapicgen/git/github.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
Labels: automerge, size: l

#7731 feat(workstations): start generating apiv1
  workstations/CHANGES.md
Labels: size: xs, api: workstations

#7733 chore: unstick renovate and remove invalid config
  .github/renovate.json
Labels: automerge, size: xs

#7736 chore(networkconnectivity): preserve policy_based_routing files
  .github/.OwlBot.yaml
Labels: kokoro:force-run, automerge, api: networkconnectivity, size: xs

#7747 chore(internal/postprocessor): don't include manifest entry for root mod
  .github/.OwlBot.lock.yaml
  internal/postprocessor/manifest.go
Labels: size: xs

#7751 chore: migrate resourcemanager v2 to owlbot
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
  internal/postprocessor/config.yaml
Labels: automerge, size: s

#7755 chore: onboard trace to owlbot
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
  internal/postprocessor/config.yaml
Labels: automerge, size: s

#7748 chore: onboard cloudtask api to owlbot
  .github/.OwlBot.yaml
  internal/gapicgen/generator/config.go
  internal/postprocessor/config.yaml
Labels: automerge, size: s

#7753 chore(storage): remove unnecessary test
  storage/integration_test.go
Labels: api: storage, size: m

#7744 fix(spanner): context timeout should be wrapped correctly
  spanner/client.go
  spanner/client_test.go
Labels: api: spanner, kokoro:force-run, size: s

#7768 chore: try to get renovate working again
  .github/renovate.json
Labels: automerge, size: xs

#7769 feat(alloydb): promote to GA
  alloydb/CHANGES.md
Labels: size: xs, api: alloydb

#7770 chore(confidentialcomputing): add config to generate apiv1alpha1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: api: confidentialcomputing, size: xs

#7737 chore(internal/postprocessor): complete MoveSnippets and remove RegenSnippets
  internal/postprocessor/config.go
  internal/postprocessor/go.mod
  internal/postprocessor/go.sum
  internal/postprocessor/main.go
  internal/postprocessor/snippets.go
Labels: size: m

#7704 test(storage): add 408 to upload conf tests
  storage/internal/test/conformance/retry_tests.json
Labels: api: storage, size: xs

#7772 chore(internal/postprocessor): update postprocessor container SHA in OwlBot.lock.yaml
  .github/.OwlBot.lock.yaml
Labels: size: xs

#7749 chore(storage): move stubs dir to storagepb
  internal/gapicgen/generator/config.go
  storage/acl.go
  storage/acl_test.go
  storage/bucket.go
  storage/bucket_test.go
  storage/grpc_client.go
  storage/hmac.go
  storage/internal/apiv2/doc.go
  storage/internal/apiv2/storage_client.go
  storage/internal/apiv2/storage_client_example_test.go
  storage/internal/apiv2/storagepb/storage.pb.go
  storage/notifications.go
  storage/storage.go
  storage/storage_test.go
Labels: automerge, size: m

#7776 chore(storage): migrate SignedURL tests
  storage/integration_test.go
Labels: api: storage, automerge, size: l

#7621 chore(storage): update client pool to be static and initialized on start (benchmarking)
  storage/internal/benchmarks/README.md
  storage/internal/benchmarks/client_pool.go
  storage/internal/benchmarks/main.go
  storage/internal/benchmarks/w1r3.go
Labels: size: m

#7780 chore(storage): clean up unused test func
  storage/integration_test.go
Labels: api: storage, automerge, size: s

#7777 chore(storage): handle zero-byte reads in gRPC
  storage/grpc_client.go
  storage/http_client.go
  storage/integration_test.go
Labels: api: storage, automerge, size: s

#7775 chore(dataproc): add dataproc/v2 to OwlBot
  .github/.OwlBot.yaml
Labels: api: dataproc, size: xs

#7782 chore(internal/postprocessor): fix pathing issues
  .github/.OwlBot.lock.yaml
  internal/postprocessor/config.go
  internal/postprocessor/manifest.go
Labels: automerge, size: s

#7783 chore(storage): migrate OC tracing test
  storage/integration_test.go
  storage/oc_test.go
Labels: api: storage, automerge, size: m

#7791 chore: CNDB CODEOWNERS and blunderbuss
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: size: xs

#7793 test(storage): revert scenario 8 conf test change
  storage/internal/test/conformance/retry_tests.json
Labels: api: storage, automerge, size: xs

#7792 chore(internal/postprocessor): add a workaround for moving new snippets
  .github/.OwlBot.lock.yaml
  internal/postprocessor/main.go
Labels: automerge, size: s

#7781 chore(storage): fix api selection [benchmarking]
  storage/internal/benchmarks/client_pool.go
  storage/internal/benchmarks/main.go
  storage/internal/benchmarks/w1r3.go
Labels: api: storage, size: m

#7787 chore(storage): migrate all remaining int tests
  storage/integration_test.go
Labels: api: storage, automerge, size: l

#7794 chore(internal/postprocessor): strip major version for scope
  .github/.OwlBot.lock.yaml
  internal/postprocessor/main.go
Labels: automerge, size: xs

#7745 docs(pubsublite): example for configuring earlier OAuth token refresh
  pubsublite/go.mod
  pubsublite/go.sum
  pubsublite/pscompat/example_test.go
Labels: automerge, api: pubsublite, size: m

#7752 chore(storage): add JSON reads [benchmarking]
  storage/internal/benchmarks/README.md
  storage/internal/benchmarks/client_pool.go
  storage/internal/benchmarks/go.mod
  storage/internal/benchmarks/go.sum
  storage/internal/benchmarks/main.go
  storage/internal/benchmarks/utils.go
  storage/internal/benchmarks/w1r3.go
Labels: api: storage, size: l

#7809 fix(spanner/spannertest): send transaction id in result metadata
  spanner/spannertest/db.go
  spanner/spannertest/inmem.go
  spanner/spannertest/integration_test.go
Labels: api: spanner, size: s

#7757 feat(firestore): EntityFilter for AND/OR queries
  firestore/integration_test.go
  firestore/query.go
  firestore/query_test.go
  firestore/util_test.go
Labels: api: firestore, size: l

#7746 fix(pubsublite): enforce minimum publisher and subscriber timeout of 2 minutes
  pubsublite/internal/wire/settings.go
  pubsublite/internal/wire/settings_test.go
  pubsublite/pscompat/settings.go
  pubsublite/pscompat/settings_test.go
Labels: automerge, api: pubsublite, size: m

#7771 chore(internal/gapicgen): remove all code related to updating google-cloud-go
  .github/.OwlBot.yaml
  internal/gapicgen/cmd/genbot/bot.go
  internal/gapicgen/cmd/genbot/generate.go
  internal/gapicgen/cmd/genbot/local.go
  internal/gapicgen/cmd/genbot/main.go
  internal/gapicgen/cmd/genbot/update.go
  internal/gapicgen/generator/config.go
  internal/gapicgen/generator/config_test.go
  internal/gapicgen/generator/gapics.go
  internal/gapicgen/generator/generator.go
  internal/gapicgen/generator/genproto.go
  internal/gapicgen/git/git.go
  internal/gapicgen/git/git_test.go
  internal/gapicgen/git/github.go
  internal/gapicgen/go.mod
  internal/gapicgen/go.sum
  internal/postprocessor/config.yaml
Labels: automerge, size: xl

#7815 chore: fix yaml parsing error
  internal/postprocessor/config.yaml
Labels: size: xl

#7804 chore(storage): change default buffer sizes to kib [benchmarking]
  storage/internal/benchmarks/README.md
  storage/internal/benchmarks/main.go
Labels: api: storage, size: s

#7819 chore(internal/postprocessor): remove moving of snippets
  internal/postprocessor/main.go
  internal/postprocessor/main_test.go
  internal/postprocessor/testdata/internal/generated/snippets/video/stitcher/apiv1/snippet_metadata.google.cloud.video.stitcher.v1.json
  internal/postprocessor/testdata/video/internal/version.go
Labels: size: m

#7827 docs(pubsublite): associate examples with the correct function
  pubsublite/pscompat/example_test.go
Labels: api: pubsublite, size: xs

#7840 chore(confidentialcomputing): add confidentialcomputing to release please
  .release-please-manifest-submodules.json
  release-please-config-yoshi-submodules.json
Labels: api: confidentialcomputing, size: xs

#7850 chore(storageinsights): add config to generate apiv1
  .github/.OwlBot.yaml
  .release-please-manifest-submodules.json
  internal/postprocessor/config.yaml
  release-please-config-yoshi-submodules.json
Labels: size: s

#7852 chore(confidentialcomputing): add config to generate apiv1
  .github/.OwlBot.yaml
  internal/postprocessor/config.yaml
Labels: api: confidentialcomputing, size: xs

#7853 feat(pubsublite): expose functions to encode/decode message event times
  pubsublite/pscompat/example_test.go
  pubsublite/pscompat/integration_test.go
  pubsublite/pscompat/message.go
  pubsublite/pscompat/message_test.go
Labels: automerge, api: pubsublite, size: m

#7855 chore(storageinsights): fix path in config.yaml
  internal/postprocessor/config.yaml
Labels: size: xs
